In [266]:
import pandas as pd
import numpy as np
import re

In [267]:
df = pd.read_csv("/Users/santiago/ih-bootcamp/proyectos/project-pandas/GSAF5.csv")

# 1. Explorando la data

In [268]:
df.shape

(5992, 24)

In [269]:
df.head(5)
#df.tail(5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             5992 non-null   object
 1   Date                    5992 non-null   object
 2   Year                    5992 non-null   int64
 3   Type                    5992 non-null   object
 4   Country                 5949 non-null   object
 5   Area                    5590 non-null   object
 6   Location                5496 non-null   object
 7   Activity                5465 non-null   object
 8   Name                    5792 non-null   object
 9   Sex                     5425 non-null   object
 10  Age                     3311 non-null   object
 11  Injury                  5965 non-null   object
 12  Fatal (Y/N)             5973 non-null   object
 13  Time                    2779 non-null   object
 14  Species                 3058 non-null   object
 15  Investigator or Source  5977 non-null   object
 16  pdf                     5992 non-null   object
 17  href formula            5991 non-null   object
 18  href                    5989 non-null   object
 19  Case Number.1           5992 non-null   object
 20  Case Number.2           5992 non-null   object
 21  original order          5992 non-null   int64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: int64(2), object(22)
memory usage: 1.1+ MB

In [271]:
# porcentaje de valores nulos por columna
df.columns=df.columns.str.replace(" ", "_")
df.columns=df.columns.str.lower()

In [272]:
nulls=list(zip(df.columns, [sum(df[x].isnull())/len(df[x])*100 for x in df]))

In [273]:
pd.DataFrame(nulls)

                         0          1
0              case_number   0.000000
1                     date   0.000000
2                     year   0.000000
3                     type   0.000000
4                  country   0.717623
5                     area   6.708945
6                 location   8.277704
7                 activity   8.795060
8                     name   3.337784
9                     sex_   9.462617
10                     age  44.742991
11                  injury   0.450601
12             fatal_(y/n)   0.317089
13                    time  53.621495
14                species_  48.965287
15  investigator_or_source   0.250334
16                     pdf   0.000000
17            href_formula   0.016689
18                    href   0.050067
19           case_number.1   0.000000
20           case_number.2   0.000000
21          original_order   0.000000
22             unnamed:_22  99.983311
23             unnamed:_23  99.966622

# Puntos a trabajar
    - Cambiar tipos de datos en variables de fecha a fecha
    - Tirar variables que no sean Ãºtiles y/o con muchos valores nulos
    - Unificar valores en variables como sex_, fatal_(y/n)
    - Limpiar valores de variable country para que sean sÃ³lo nombres de paÃ­ses, cambiar valores de regiones por NAs
    - Completar variables con muchos nulos con informaciÃ³n de otra fuente.

## trabajando con los valores nulos

### Tirando unnamed:_23 y unnamed:_22

In [274]:
print(df["unnamed:_23"].unique(), df["unnamed:_22"].unique())

[nan 'Teramo' 'change filename'] [nan 'stopped here']

In [275]:
df[df["unnamed:_23"].isnull()!=True]

,case_number,date,year,type,country,area,location,activity,name,sex_,...,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,unnamed:_22,unnamed:_23
4182,1952.07.13,13-Jul-52,1952,Provoked,USA,California,"San Diego, San Diego County",Fishing,"Gerald Howard, on board sportsfishing boat Ter...",M,...,NaN,"L.A. Times, 7/14/1952",1952.07.13-Howard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.07.13,1952.07.13,1811,NaN,Teramo
5585,1879.03.10,10-Mar-1879,1879,Invalid,AUSTRALIA,New South Wales,Near Sydney,The steamship Bonnie Dundee lost in collision,Cabin boy of the Bonnie Dundee,M,...,NaN,"Star, 3/22/1879",1879.03.10-Bonnie-Dundee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1879.03.10,1879.03.10,408,NaN,change filename

In [276]:
df[df["unnamed:_22"].isnull()!=True]

,case_number,date,year,type,country,area,location,activity,name,sex_,...,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,unnamed:_22,unnamed:_23
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,...,NaN,globalsurfnews.com,2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.18,2006.06.18,4746,stopped here,NaN

In [277]:
#al parecer no tienen informaciÃ³n relevante las columnas "unnamed:_22" y "unnamed:_23"
df.drop(columns=["unnamed:_22", "unnamed:_23","case_number.1", "case_number.2", "href_formula"], inplace=True)

## Trabajo por variables
### investigator_or_source

In [278]:
df.investigator_or_source.nunique()

4752

In [279]:
set(df.investigator_or_source.unique())

{nan,
 'L. Kumpe, R. Mcauley',
 'Ocala Star Banner, 8/30/1972',
 'Palm Beach Post, 11/16/2015',
 'P. Lynch, N. Doveton, G. Wolfe, M.Levine, GSAF ',
 'Sydney Morning Herald, 7/7/1936; V.M. Coppleson (1958), p.244',
 'Nelson Examiner & New Zealand Chronicle, 4/24/1869',
 'Canberra Times, 9/8/1962',
 'Canberra Times, 6/26/1972',
 'D.G. McComb',
 'C. Creswell, GSAF; Washington Post, 10/7/1883, p.2',
 'Long Beach Independent, 1/281964 ',
 'Clicanoo, 7/15/2013',
 'The Queenslander, 12/17/ 1921',
 'Stuff.co.nz, 1/18/2013',
 'TC Palm, 2/3/2010',
 'WFTV,  5/27/2015',
 'V.M. Coppleson (1962), p.206',
 'Reno Evening Gazette, 7/11/1879',
 'B.A. Wright',
 'Gulfport Herald, 7/12/1963; SAF Case #1218',
 'G. Cliff & B. Davis, NSB',
 'A. Cobb & E. Ritter, GSAF',
 'A. Hartman, M. Levine, GSAF; Cape Argus, 4/26/1974',
 'BBC, 9/9/2014',
 'Big Island Now, 12/11/2013',
 'Sydney Morning Herald, 4/4/1961 ; Launceston Examiner; H.D. Baldridge, pp.133-134',
 'The Argus, 11/6/1937',
 'R. Collier, p.172',
 'C. Moore. GSAF',
 'The Times, 6/19/2014',
 'Fiji Times, 2/17/1964',
 'B.W. Coad & L.A.J. Al-Hassan',
 'J. Bass; M. Levine, GSAF',
 'Daily Guide, 8/20/2007',
 'A. Xuereb',
 'Press clippings',
 'M. Bowker; W. Pople, NSB',
 'Bardanis citing Embros, 9/23/1901',
 'D. Miller & R. Collier; R. Collier, pp.42-44; H.D. Baldridge, p.78;',
 'globalsurfnews.com',
 ' M. Levine, GSAF ',
 'Sydney Morning Herald, 12/21/1960; V.M. Coppleson (1962), p.246 ',
 'E. Clark; P. Gilbert; V.M. Coppleson (1962), p.252',
 'Morning Bulletin, 1/1/1917',
 'Miami Daily News, 5/7/1957',
 'A. MacCormick, p.56; H. Edwards, pp.11 & 159',
 'M. Vorenberg; R. Greer, M.D.',
 'Palm Beach Post, 4/13/2016',
 'Canberra Times, 9/15/1979',
 'D. Miller & R. Collier; R. Collier, pp. 21-24    ',
 'The Advertiser, 3/25/1918',
 'W. B. Orme',
 'Newcastle Herald, 5/22/2014',
 'A. L. Tester',
 'History of the Pyrates, by D. Defoe, Vol. 2, p.28',
 'LA Times, 7/28/1989',
 'R.N. Lea & D. Miller; Herder, p. 1-3; R. Collier, pp.89-91; A. MacCormick, pp.80-81',
 'C. Black; H.D. Baldridge (1994) ISAF Case #654',
 'F. Poli, p.9',
 'T. Mori, KHON2, 8/18/2013',
 'Daytona Beach Morning Journal, 11/2/1974',
 'Orange County Register, 3/13/2016',
 'Western Argus, 9/26/1922',
 'Ahram Online, 6/4/2016',
 'H.D. Baldridge (1994) SAF Case #1475',
 'L. Schultz & M. Malin, p.562; SAF Case #819',
 'P.M. Lopes, GSAF, JC, 5/23/2004',
 'R.F. Hutton (1959); D. Baldridge, p.171; T. Helm, p.226; SAF Case #624',
 'C. Creswell, GSAF, J. Barnes',
 'M. Szpilman, p.139',
 'W.H. Gregg, p.22;      L. Schultz & M. Malin, p.529',
 'Miami Herald, 12/27/1997',
 "L'Express, 5/2/2007",
 'H.R. Janisch (1885), Extracts from the St. Helena Archives',
 'J. Oetzel, Skin Diver Magazine, March 1956, p.19 ',
 'PNG Post-Courier, 6/13/2002, p.5',
 'J. Horton, West Volusia Bulletin, 6/6/2012',
 'New York Times, 6/21/1896',
 'R. Fernicola, GSAF ',
 'Elyria Republican, 3/18/1880',
 'Palm Beach Post, 9/28/1953',
 'S. Petersohn, Orlando Sentinel, 8/6/1999; M.I. Johnson, Daytona Beach News Journal, 8/6/1999, p.3C ',
 'R.N. Lea & D. Miller; R. Collier, p.81',
 'tbo.com',
 'R. A Smith; G.P. Whitley (1951), p.194, cites Sunday Herald (Sydney), 12/17/1950; V.M. Coppleson (1958), pp.94 & 239]',
 'The Times, 6/25/1817',
 'Orange County Register, 1/28/2998',
 'Times Live, 4/1/2015',
 'S. Petersohn;J. Wheeler, 13 News, 5/4/2010',
 'Press Report dated 2-14-2002',
 'A. Anderson, M.D. / Lt. Col. R.S. Hunt, Royal Army Medical Corp, p.84 ',
 'IOL News, 12/29/2014',
 'Soda Springs Sun, 12/19/1940',
 'Stevens Point Daily Journal, 9/26/1914, p.2 ',
 'Florida Today, 9/30/2013',
 'Times (London), 9/2/1937; Fairfax, pp. 66-67',
 'Globo, 3/31/2015',
 'A. Sharpe, pp.135-136',
 'Ruston Daily Leader, 2/28/1977; A. Sharpe, p.86',
 "Kaua'i Police Department",
 'New York Times, 8/27/1931, p.7; V.M. Coppleson (1958), p.258',
 "Cork Examiner, 8/17/1867; Whaleman's Shipping List, 9/24;1867",
 'J. Engel, SRI & S. Fox, Deep Blue',
 'G. Lee, KGMB9.com',
 'Union County Journal, 12/22/1887',
 'Moreton Bay Courier, 12.4/1847',
 'K. Morelli, Tampa Tribune, 9/6/1999',
 'TC Palm, 3/23/2014',
 'Brisbane Courier, 1/7/1895, p.5',
 'Perth Now, 1/7/2013',
 'S. Connelly',
 'R. Rocconi; A. De Maddalena & C. Moore, GSAF',
 'P. Barron; Goulburn Evening Post; J. Green, p.35',
 'Daily Telegraph, 11/12/1997, p.5',
 'NBC2 News, 8/5/2013',
 'Perth Now, 10/30/2015',
 'B. Coppin, M. Levine, GSAF',
 'The Mirror (London); Orlando Sentinel, 5/28, 1997, p.C3',
 'Northern Miner, 5/27/1923',
 'Advertiser, 1/12/1994, p.18',
 'T. Wallett, p.37-38',
 'Brisbane Courier, 2/8/1915',
 'Florida Today, 5/22/2016',
 'Miami Herald, 6/20/1965; SAF Case #1372',
 'G.P. Whitley, citing Lone Hand, 12/1/1910, p.134',
 'The Argus, 4/9/1855',
 'R. Kahn, M. Levine, GSAF',
 'C. Sugidono, The Maui News, 12/2/2013',
 'Honolulu Advertiser, 9/10/08',
 'Abilene Reporter-News, 6/9/1977',
 'E. Pace, GSAF',
 'St Augustine Record, 6/19/2007',
 'D. McGee, J. Quillian, W. M. Stephens; V.M. Coppleson (1962), p.249; H.D. Baldridge, p.183',
 'Florida Times-Union, 8/14/2000; Orlando Sentinel, 8/15/2000, p.D3',
 'C. Creswell, GSAF; Charlotte Observer, 8/12/1995',
 'L. Schultz & M. Malin, p.534',
 'Herald Express (L.A.), 7/25/1959',
 'Post and Courier, 8/11/2013',
 'D. Davies, p.114; A. Cowan, M. Levine, GSAF',
 'G.P. Whitley, p.263; V.M. Coppleson (1958), p.244',
 'Edinburgh Advertiser. 2/3/1818',
 'H. Kariya &T. Abe; P. Gilbert, L. Schultz & S. Springer (1960); K. Nakaya',
 'Mercury News, 8/15/2010',
 'R.I. DeSilva, GSAF',
 'P. W. Gilbert; SAF Case #1435',
 'Lt. Col. R.S. Hunt of the Royal Army Medical Corp',
 'Orlando Sentinel, 10/24/1992, p.A5; G. Ambrose, pp.54-60; A. MacCormick, p.195; J. Borg, p.82; L. Taylor (1993), pp.114-115',
 'M. McDiarmid, p.67',
 'Illwara Mercury',
 'C. Dummitt, Palm Beach Post. 9/3/1992',
 'J. Borg, p.79; L. Taylor (1993), pp.110-111',
 'V.M. Coppleson (1958), p.181',
 'News 24, 6/23/2016',
 'J. Royle, et. al. (1997)',
 'J. Musick',
 'L. Schultz & M. Malin, p.557; SAF Case #833',
 'Otago Witness, 2/17/1877',
 'T. Wallett, p.25',
 'CBS Miami, 6/6/2013',
 'Letter from Captain R. G. Rehrer in letter to G.A. Llano in Sharks and Survival, pp.381-382; V.M. Coppleson (1962), p.257',
 'Channel 9; Northern Territory News, 7/20/2004, p.10 ',
 'R. Collier, p.140',
 'Sydney Morning Herald, 4/23/1936',
 'DiariodeAvisos, 7/25/2014',
 'The Hobarton Mercury, 2/12/1855',
 'Pittsburgh Press, 2/21/1948/ V.M. Coppleson (1962), p.258',
 'Virgin Islands Daily News, 1/17/1966; SAF Case #1399',
 'W.H. Gregg, p.19;      L. Schultz & M. Malin, p.533',
 'G. Hubbell; J. Castro; Ocala Star-Banner, 9/22/1995; Orlando Sentinel, 9/23/1995, p.D1\n',
 'Sydney Daily Telegraph, 1/15/1962 ',
 ' V.M. Coppleson (1958), p.112',
 'Brisbane Courier, 1/24/1882',
 'C. Black, GSAF; V.M. Coppleson (1958), p.105',
 'C. Lancaster, Orlando Sentinel, 8/24/1995, p.D1',
 'Miami Herald, 6/22/1983, p.2B',
 'F. Dennis, p.20',
 'Tri-City Herald, 4/21/1969',
 'J. Martinez, Corpus Christi Caller Times, 7/19/2011',
 'Orlando Sentinel, 4/22/2003, B3',
 'Il Gazzettino, 6/28/2012',
 'WFTV. 11/17/2015',
 'T. Jerome, GSAF; Daytona Beach News Journal,, 6/11/2004, p.1C',
 'Orlando Sentinel, 9/9/2001',
 'D. Cervantes, Star',
 'Jornal Pequeno, 1/26/2009',
 'Cairns Post, 10/29/1926',
 'H.D. Baldridge, p.197',
 'The Sowetan. 7/9/2010',
 'Adelaide News, 1/12/1962',
 'W.H. Tobert',
 'H.D. Baldridge, p.162; SAF Case #1124',
 'Post & Courier, 9/12/2005',
 'H.D. Baldridge, pp.177 & 185',
 'Mrs. Crewe, B. Lipschitz, M. Levine, GSAF',
 'East London Dispatch, 11/16/1959',
 'R. Collier, pp.116-118',
 'Northern Territory News, 10/14/2008',
 'H.D.Baldridge, SAF Case #1531',
 'The Mercury, 9/14/1954',
 'News & Courier, 7/14/1956; V.M. Coppleson (1958), pp.  153 & 255',
 'Miami Herald, 7/21/1982, p.1D',
 'Miami Herald, 1/25/1996',
 'D. Miller & R. Collier, V.M. Coppleson (1958), p.254; T. Helm, p.232',
 'J. Oetzel; H. D. Baldridge, p.165',
 'M. McKee,Orlando Sentinel, 7/30/1985, p.A1',
 'Washington Evening Star, 6/17/1959; V.M. Coppleson (1962), p.253',
 'E. Ritter. GSAF',
 'E. Tiira',
 'N. Bevan, icwales.icnetwork.co.uk, 1/28/2006',
 'A. LeRoux, M. Levine, GSAF; L. Green; G.Wilson',
 'Providence Journal, 8/7/1983',
 'Inquisitr.com, 6/9/2014',
 'Orlando Sentinel, 112/1/1993, p.A9',
 'http://www.foldabikes.com/CurrentEvents/Story/Florida.html',
 'A. De Maddalena;      R. Rocconi',
 'H.D. Baldridge (1994) SAF Case #1521',
 'E. Dawkins, M.D.',
 'S. Samuels',
 'A. Brenneka, Shark Attack Surviors',
 'Watertown Daily Times, 7/8/2011',
 'E. Pace, FSAF; Sun Sentinel, 9/22/1991, p.3B',
 'Courier Pigeon, 8/30/2011',
 'Clay Creswell, GSAF; Topsail Voice, 9/19/2001',
 'Sun Sentinel, 8/31/2014',
 'Papuan Villager, 11/1940',
 'G. Balazs; Allen, p.109',
 'V.M. Coppleson, p.452; G.P. Whitley',
 'NZ Herald, 12/11/2007',
 'JC Online, 6/26/2023',
 'J. Borg, p.76; L. Taylor (1993), pp.106-107; Windsurfing Magazine, Sept/Oct 1993',
 "Ma'an News Agency, 5/25/2013",
 'R.D. Weeks, GSAF; Otago Daily Times, 2/6/1964 & 2/7/1964',
 'KRT Wire, 4/24/2006',
 'Washington Post, 8/16/1983',
 'NY Times, 11/6/1975, p.8',
 'Timaru Herald, 11/8/1892',
 'R. Guy, M. Levine, GSAF',
 'coralsea-wrecks.com',
 'H.D. Baldridge, SAF Case #1466',
 'D. Davies',
 'Galveston Daily News, 7/21/1889',
 'Daily Dispatch, 4/10/2009',
 'A.M. Rapson, p.150; L. Schultz & M. Malin, p.544',
 "D. Davies & J. D'Aubrey, GSAF",
 'Lima News, 9/27/1898',
 'The Advertiser, 12/30/1996, p.3',
 'Colonial Times, 5/24/1845',
 'A.M. Rapson, p.149; L. Schultz & M. Malin, p.544',
 'LA Times, 3/25/1951 ',
 'Morning Post, 4/20/1906',
 'Captain A. Anderson,  Natal Mercury, 12/31/1921; M. Levine, GSAF',
 'R. McKenzie, Sunday Mail, 9/6/1987, p.11',
 'G.P. Whitley (1951), p.194; V.M. Coppleson (1958), p.239; A. Sharpe, pp.38 & 97',
 'S. Petersohn, GSAF; Orlando Sentinel, 8/15/2002, p.B3',
 'Natal Parks Board, J. Daniel; W. Pople, G. Charter, GSAF',
 'V.M. Coppleson (1958), p.110 [ Note: Coppleson had no concrete evidence about this incident; he heard only "vague reports".',
 'L. Schultz & M. Malin, p.562; SAF Case #870 ',
 'Linfo.re, 8/5/2012',
 'Orlando Sentinel, 6/19/1995, p.B3; Fort Pierce Tribune,  6/19/1995',
 'D. Miller & R. Collier, R. Collier, pp.67-69; J. McCosker & R.N. Lea; NY Times, 12/7/1975, p.30, col.1',
 'R. Collier, GSAF /                   M Michaelson, SRI ',
 'A.Resciniti, p.109',
 'Daily Mirror (Sydney) 11/23/1959; G.P. Whitley; P. Gilbert, L. Schultz & S. Springer (1960); J. Green, p.35',
 'D. Miller & R. Collier, R. Collier, pp.57-59; J. McCosker & R.N. Lea',
 'G. Gore & M. Sturdevant',
 'San Diego Union, 7/26/1959',
 'D. Martinez, Tico Times, 6/21/2011',
 'The Stuart (FL) News, 5/17/1998',
 'Star, 3/22/1879',
 'Evening Independent, 6/8/1936',
 'Brevard Times, 10/19/2012',
 'NY Times, 8/22/1894 ',
 'V.M. Coppleson (1958), pp.71, 174-175 & 236; A. Sharpe, p.74',
 'Star, 3/18/1909',
 'Captain T. Falcon-Barker',
 'R.D. Weeks, GSAF',
 'P. LaMee, Orlando Sentinel, 8/12/1995, p.D.1',
 'Miami Herald, 9/28/1982',
 'Charleston Daily Mail, 9/10/1973',
 'Sydney Daily Telegraph, 2/11/1960',
 'Clicanoo, 10/5/2011',
 'S. Petersohn, GSAF; scubaradio.com; Orlando Sentinel, 4/14/2001, p.A1',
 'R.D. Weeks, GSAF; Otago Daily Times, 12/24/1907',
 'Rome News Tribune, 7/31/1974',
 'Indiana Messenger, 9/16/1903',
 'Gaffney Ledger, 5/2/2005',
 'P.M. Lopez, GSAF; O. Gadig; JC, 5/3/1999',
 'Folha de S.Paul, 6/10/1998',
 'Western Mail, 11/29/1923; V.M. Coppleson (1933); G.P. Whitley (1940), p.260;  G.P. Whitley (1951), p 185; A. Sharpe, p.129',
 'Coppleson (1962), p.247',
 'Gilbert P. Whitley (1951), p.193; V.M. Coppleson (1958), p.239. NOTE: Whitley records location as Coolangatta',
 'C. Creswell, GSAF; Wilmington Morning Star; Charlotte Observer, 8/23/2000, p.2B',
 'S. Hammerton, M. Levine, GSAF; W. Pople,  G. Charter, NSB',
 'Nova transcript; Hawaii Department of Land and Natural Resources ',
 'M. I. Johnson, Daytona Beach News Journal',
 'Hawaii News Now, 11/5/2012',
 'The Gleaner, 7/27/1980',
 'Macleay Argus, 8/10/2010',
 'New Zealand Herald, 1/10/2009',
 'KHON2, 10/17/2015',
 'Iowa City Citizen, 12/23/1910',
 'R.F. Hutton',
 'J. Borg, p.74',
 'Local10.com, 6/1/2014',
 'WPTV, 6/13/2011',
 'H. D. Baldridge (1994), SAF Case #440 listed incident as "Questionable"',
 'LA Times, 9/5/1955 editon ',
 'Daily Telegraph, 7/26/1996, p.15; K. Lavalli & O. Goffman',
 'Charlotte Observer, 5/28/1987 ',
 'L. Taylor (1993), pp.100-101',
 'Seychelles Forum',
 'Globo, 6/9/1997',
 'R.F. Hutton; T. Helm, p. 231 ',
 'The West Australian, 6/3/1895',
 'T. Peake, GSAF; Sunday Times (Perth) 3/7/2004, p.19',
 'W.v.Rensberg, M. Levine, GSAF',
 'News4JAX, 9/1/2011',
 'D. Ljusic',
 'J. Wong, GSAF; Daily Telegraph Mirror, 6/3/1995;  ',
 'San Francisco Chronicle, 10/7/1959n; D. Miller & R. Collier;  R. Collier, pp.25-26; P. Gilbert, L. Schultz & S. Springer (1960); H.D. Baldridge, p.70',
 'H.D. Baldridge (1994) SAF Case #1478',
 'J. R. Varma; M. Levine, GSAF',
 'Action News, 7/25/2013',
 'Mentioned in letter from L. S. Mowbray dated 4/24/1959; L. Schultz & M. Malin, p.516',
 'The Western Champion, 4/14/1928',
 'P.Tichener',
 'Maitland Mercury, 8/25/1855',
 'Daniell Washington',
 'Yahoo News, 6/19/2015',
 'Courthouse News Service, 11/18/2015',
 'NY Post, 7/16/2010',
 'G. Charter, B. Davis,  NSB',
 'E. Clark (1960); M. Vorenberg; R. Skocik, pp.173-174; H.D. Baldridge, pp. 25, 62, 73 & 164',
 'V.M. Coppleson  (1958), p.259 ',
 'Pinchot in To the South Seas, citing M. Craig who reports 6 incidents in 1923-24 including this one',
 'Grand Forks Herald, 1/27/2915',
 'El Universo, 5/16/2013',
 'Charlotte Observer, 7/17/1997, p.2C; C. Creswell, GSAF',
 'H.D. Baldridge (1994), SAF Case #1630',
 'C.Delneo, C. Creswell, M. Levine, R. Collier, GSAF',
 'Brisbane Courier, 5/8/1928',
 'Atlanta Constitution, 5/17/1910, p.5',
 'The Age, 2/8/1977',
 'E. Clark; R. Skocik, pp.172-173; H.D. Baldridge, p.26',
 'Indian Express, 6/30/1946',
 'Fresno Bee, 10/31/1911',
 'Townsville Daily Bulletin, 6/9/1933 ',
 'Tioga Eagle, 9/10/1845',
 'Sarasota Herald Tribune, 6/2/1975',
 'The Hawaii Channel',
 'J. Musick,',
 'A. Bleakley; A.M. Rapson, p.150 ',
 'G. Taylor, Orlando Sentinel, 10/12/1988, p.D3',
 'Evening Star (Washington D.C.), 7/7/1958, p. A10; G.A. Llano in Sharks and Survival, pp.382-383; V.M. Coppleson (1962), p.259',
 'A. De Maddalena; Gianturco (1978)',
 'Daytona Beach News-Journal, 8/7/2010',
 'Brisbane Courier, 7/6/1920',
 'Sydney Morning Herald, 10/1/1890',
 'Star Bulletin, 10/19/2009',
 'A. De Maddalena; F. Serena (pers. Comm.)',
 'H.D. Baldridge, SAF Case #1477',
 'Brisbane Courier, 1/28/1909',
 'The Age, 10/31/2009',
 'Ref in New York Herald Tribune, 8/23/1960; V.M. Coppleson (1962), p.155',
 'Atlanta Journal-Constitution, 9/5/2001; Florida Times-Union, 9/5/2001',
 'Bellingen Courier-Sun; J. Green, p.35',
 'V.M. Coppleson.N13. (1933); V.M. Coppleson (1958), p.76 & 229',
 'A. De Maddalena; Doderlein (1881)',
 'Bali Waves',
 'C. Moore citing R. Peirce',
 'CNN; Orlando Sentinel, 4/18/1998, p.D7;   Tallahassee Democrat, 4/19/1998',
 'Courier-Mail, 2/5/1993, p.7',
 'Key West Citizen, 7/26/2001',
 'Hawaiian Gazette, 11/1/1898',
 'Cape Mercantile Advertiser, 1/25/1887, M. Levine, GSAF',
 'Nortnern Standard, 8/4/1936',
 "K. O'keefe",
 'C. Dudley, R.D. Weeks, GSAF; H.D. Baldridge, SAF Case #1467; Otago Daily Times, 12/2/1963, p.7',
 'J. Steel (1989)',
 'NY World -Telegram & Sun, 1/28/1959;  Note: V.M. Coppleson (1962), p.246, records the date as 3/5/1959',
 'G.L. Morris; Post Herald (Birmingham, Alabama) 5/18/1961; V.M. Coppleson (1962), p.249',
 'Northern Territory News, 7/26/2003, p.1',
 'South Pacific Post, 4/20/1955',
 'KGTV',
 'P. Landsberg, M.D.',
 'H.D.Baldridge, SAF Case #1538',
 'Times-Courier (Lae), 3/6/1963',
 'A. De Maddalena; Anon. (1954), Soldo & Jardas (2000)',
 'V.M. Coppleson.N7.(1933); V.M. Coppleson (1958), pp.63 & 230; A. Sharpe, pp.58-59;  G.A. Llano, pp.160-164',
 'Mainichi Shimbun, 7/17/2004 ',
 'W. Monk, M. Levine, GSAF',
 'V.M. Coppleson (1958), pp.144-146 ',
 'S. Petersohn',
 'ABC action News, 7/7/2015',
 'Sunday Times, 2/19/1989',
 'News4Jax, 5/19/2016',
 'E. Lombard, M. Levine, GSAF',
 'J. Emory; Caribbean Net,  4/142009',
 'Naval Historical Center',
 'Les Nouvelles Calï¿½donie, 4/28/2008 & 4/29/2008',
 'ABC-Spain, 7/25/2009',
 'Florida Today, 12/14/2007',
 'East London Daily Dispatch, 10/20/1998',
 'News-Press.com ',
 'Brisbane Times, 6/28/2009',
 'The Capricornian, 5/1/1886',
 'Advertiser, 1/12/1994,p.18',
 'C. Black, GSAF; J. Green, p.36',
 'St. Petersburg Times, 11/10/1983',
 'H. Taunton; N. Bartlett,  pp. 233-234',
 'Sun Sentinel, 5/8/2009',
 'R.D. Weeks, GSAF; Otago Daily Times, 2/20/1968; H.D. Baldridge (1994) SAF Case #1525',
 'The Mercury, 2/19/1877',
 'Australian Town & Country Journal, 12/15/1877',
 'NSRI, 7/6/2012',
 'Times of India, 2/5/2012',
 'Captain B. H. Kean',
 'S. Naidoo, Dr. M. Raj, Dr. Motala, M. Levine, GSAF; G. Charter, B. Davis, NSB',
 'Lt. Col. R. S. Hunt, pp.81-82',
 'P. Gilbert, L. Schultz & S. Springer (1960)',
 'V.M. Coppleson.N.21.(1933); V.M. Coppleson (1958), p.230; NYTimes, 1/5/1927',
 'Sydney Daily Telegraph, 4/21/1962 ',
 'WMBF News, 6/14/2013',
 'D. Miller & R. Collier; R. Collier, p. 76-79; J. McCosker & R.N. Lea; K. Doudt',
 'The Mail, 2/9/1929; G.P. Whitley;  SAF Case #505',
 'West Australian, 11/13/2013',
 'Daily Telegraph, 12/18/2007',
 'A. Heydorn, ORI',
 'wpmi.com',
 'Daytona Beach Morning Journal, 7/9/1980',
 'Coffs Coast Advocate, 5/4/2013',
 ' A. Sharpe, pp.124-125; Sydney Morning Herald, 2/3/2001 ed.',
 'G. H. Balazs & A. H. Kam; V.M. Coppleson (1958), p.259, J. Borg, p.68; L. Taylor (1993), pp.94-95',
 'R. Forrester, M. Levine, GSAF',
 'G.. Filtzer; G. Ambrose, pp.8-17; J. Borg, p.64',
 'Evening Indeipendent, 6/10/1968, p.3',
 'JC Online, 6/25/2012',
 'The Age, 2/11/1975',
 'SAF Case #1109',
 'M. Shields',
 'E. Ritter, GSAF; iwindsurf.co.uk',
 'C. Creswell, GSAF; WWAY, 8/24/2014',
 'M. Hely, E. Kerns, M. Levine, GSAF;  G.D. Campbell; D. Davies, pp.102-108; Tim Wallett',
 'Letter from Captain Raoul G. Rehrer in letter to G.A. Llano in Sharks and Survival, pp.381-382; V.M. Coppleson (1962), p.257',
 'T. Peake, GSAF; Sunday Times (Perth)  6/27/2004, p.11',
 'Daily News (Durban), 1/29/1974; GSAF',
 'West Australian, 9/15/2016',
 'Port Elizabeth Museum Archives',
 'Charlotte Observer, 6/24/1992, p.1C & 8/8/1992, p.2C',
 'V.M. Coppleson (1958), pp. 248 & 266; A.M. Rapson, p.149',
 'fptci.com, 6/23/2011',
 'S. Petersohn, GSAF; Orlando Sentinel, 5/16;2003, p.C3',
 'J. Borg, p.71; L. Taylor (1993), pp.96-97',
 'Taranaki Herald, 12/28/1900',
 'D. Salamone, GSAF',
 'O. Gadig; Globo, 4/24/1997',
 'surfguru.com.br ',
 'St. Paul Dispatch, 10/27/1965',
 'T. Toft, M. Levine, GSAF',
 'Brisbane Courier, 12/15/1877',
 'Hawaii News Now, 6/26/2012',
 'USS Gambier Bay archives',
 '   San Jose Mercury News, 1/6/1995, p.12A ',
 'H.L. Johnson; SAF Case #1353',
 'R.S. Jones',
 'South Pacific Post (Port Moresby) 3/4/1962; L. Malcolmson, Fisheries Officer ',
 'SAF Case #1497; R. Collier, p. xxv; H.D. Baldridge, p.185',
 'C. Creswell, GSAF; J. Hair, p.27',
 'The Advertiser, 2/13/1933',
 'Atlanta Constitution, 7/25/1912',
 'Aftenposten, 7/18/2007',
 'Herald Sun, 11/12/1992, p.39',
 'H. Cornu',
 'S. Heywood',
 'G. Ferrario; J. Mendoza, Cameron County Parks; The Herald (Brownsville),  4/11/2005',
 'G.P. Whitley (1951), p. 193; V.M. Coppleson (1958), p.70; A. Sharpe, pp.72-73; A. MacCormick, pp.34-35',
 'A. Costellano, ABC News, 7/31/202',
 'The West, 3/16/2009',
 'V.M. Coppleson (1958), p.262',
 'ABCS; Manitoba Free-Press, 1/13/1925',
 'M. Levine, GSAF; J. Wallace,ORI; T. Wallett, p.40-41',
 'P. Kemp & T. Peake, GSAF',
 'Clearfield Progress, 5/27/1931',
 'A. MacCormick, p.227',
 'A. De Maddalena; De Maddalena (2001), N. Montoya (pers. comm.)',
 'The Gleaner (Jamaica), 4/21/1892',
 'Reported byTimes of India, 11 September 1959; V.M. Coppleson (1952), p.247; Webster, p.67',
 'J. Fayrer, M.D., pp.257-260 ',
 'Miami Herald, 8/8/2007',
 '7NewsSydney, 4/22/2013',

### Country

In [280]:
df.country=df.country.str.lower()
df.country.unique()

array(['usa', 'australia', 'new caledonia', 'reunion', 'bahamas', 'spain',
       'china', 'japan', 'columbia', 'south africa', 'egypt',
       'new zealand', 'indonesia', 'french polynesia', 'cape verde',
       'fiji', 'brazil', 'dominican republic', 'cayman islands',
       'united arab emirates', 'aruba', 'mozambique', 'thailand',
       'puerto rico', 'italy', 'mexico', 'atlantic ocean', 'greece',
       'mauritius', nan, 'st. martin', 'france', 'ecuador',
       'papua new guinea', 'trinidad & tobago', 'kiribati', 'israel',
       'diego garcia', 'taiwan', 'jamaica', 'palestinian territories',
       'guam', 'seychelles', 'belize', 'philippines', 'nigeria', 'tonga',
       'scotland', 'canada', 'croatia', 'saudi arabia', 'chile',
       'antigua', 'kenya', 'russia', 'turks & caicos', 'costa rica',
       'united kingdom', 'malaysia', 'united arab emirates (uae)',
       'samoa', 'azores', 'solomon islands', 'south korea', 'malta',
       'vietnam', 'madagascar', 'panama', 'somalia', 'nevis', 'cuba',
       'england', 'british virgin islands', 'norway', 'senegal', 'yemen',
       'gulf of aden', 'sierra leone', 'st. maartin', 'grand cayman',
       'liberia', 'vanuatu', 'mexico ', 'honduras', 'venezuela',
       'sri lanka', ' tonga', 'uruguay', 'india', 'micronesia',
       'caribbean sea', 'okinawa', 'tanzania', 'marshall islands',
       'egypt / israel', 'northern arabian sea', 'hong kong',
       'el salvador', 'angola', 'bermuda', 'montenegro', 'iran',
       'tunisia', 'namibia', 'north atlantic ocean', 'portugal',
       'south china sea', 'bangladesh', 'palau', 'western samoa',
       'pacific ocean ', 'british isles', 'grenada', 'iraq', 'turkey',
       'singapore', 'new britain', 'sudan', 'johnston island',
       'south pacific ocean', 'new guinea', 'red sea',
       'north pacific ocean', 'federated states of micronesia',
       'mid atlantic ocean', 'admiralty islands', 'british west indies',
       'south atlantic ocean', 'persian gulf', 'red sea / indian ocean',
       'pacific ocean', 'north sea', 'nicaragua ', 'maldive islands',
       'american samoa', 'andaman / nicobar islandas', 'gabon', 'mayotte',
       'north atlantic ocean ', 'the balkans', 'sudan?', 'argentina',
       'martinique', 'indian ocean', 'guatemala', 'netherlands antilles',
       'northern mariana islands', 'iran / iraq', 'java', ' philippines',
       'nicaragua', 'central pacific', 'solomon islands / vanuatu',
       'southwest pacific ocean', 'bay of bengal', 'mid-pacifc ocean',
       'slovenia', 'curacao', 'italy / croatia', 'barbados', 'monaco',
       'guyana', 'haiti', 'san domingo', 'ireland', 'kuwait', 'libya',
       'yemen ', 'mediterranean sea?', 'falkland islands', 'crete',
       'cyprus', 'egypt ', 'burma', 'lebanon', 'paraguay',
       'british new guinea', 'ocean', 'georgia', 'syria', 'tuvalu',
       'indian ocean?', 'guinea', 'equatorial guinea / cameroon',
       'cook islands', 'algeria', 'coast of africa', 'tasman sea',
       'ghana', 'st helena', 'greenland', 'mediterranean sea', 'sweden',
       'iceland', 'between portugal & india', 'djibouti', 'bahrein',
       'korea', 'red sea?', 'asia?', 'ceylon (sri lanka)'], dtype=object)

In [281]:

df.country=[re.sub(r"(/ \w* \w*)|(/ \w*)|\?| \(\w* \w*\)", "", str(x)) for x in df.country]
df.country=[re.sub(r".*ocean.*", "", str(x)) for x in df.country]

# Casos especÃ­ficos
df.country=df.country.replace("between portugal & india", "").replace("asia", "").replace("united arab emirates (uae)", "united arab emirates")
df.country=df.country.replace("gulf of aden", "yemen").replace("tasman sea", "australia")
df.country=df.country.replace("coast of africa", "").replace("mediterranean sea", "").replace("red sea", "egypt")

In [282]:
#casos que hay que revisar mas: "diego garcia"

## Type

In [283]:
# Unificando boating y boat para reducir una categorÃ­a
df.type.unique()
df.type=np.where(df.type=='Boating', 'Boat',df.type)

## Sex

In [284]:
df.sex_.unique()

array(['M', nan, 'F', 'M ', 'lli', 'N', '.'], dtype=object)

In [285]:
# Revisando y cambiando casos atÃ­picos lli se cambia por M por el 
# nombre (se asume que se Brian se identifica como hombre).
df.sex_=df.sex_.replace('M ', 'M').replace("lli", "M").replace('.', 'nan').replace('N', 'nan')
df.sex_.value_counts()

M      4838
F       585
nan       2
Name: sex_, dtype: int64

## Activity

In [286]:
# Oh no, son muchas actividades diferentes. A continuaciÃ³n se intenta reducirlas lo mÃ¡s posible
df.activity.nunique()

1492

In [287]:
set(df.activity.unique())

{nan,
 'Surfing on "chest board" (boogie board?)',
 'Collecting shells',
 'Suicide',
 'Bathing in knee-deep water',
 'Fishing for sharks',
 "Sinking of the 40' Esperanza off St. Maartin with 36 refugees on board",
 'Spearfishing & had just speared a ulua',
 'Spearfishing & holding catch',
 'Swimming / surfing',
 'Exercising his dog in the shallows',
 'Swimming, attempting to rescue a girl  believed to be drowning',
 'Floating on his back in an inner tube',
 'Skin diving ',
 'Collecting beche-de-mer',
 "Overcome by CO fumes, fell overboard from 36' fishing cruiser & prop slashed arm",
 'Fishing, standing in water next to purse net',
 'Ran into the water',
 'Wading after stray fish from seine netterï¿½s catch',
 'B-24 aircraft crashed  into the sea',
 'Floating with life preserver after his boat foundered',
 'Wooden fishing boat',
 'Body boarding',
 'Thrown into water from fishing dinghy',
 'Free diving & spearfishing ',
 'Pulling hooked salmon to boat',
 'Boating',
 'Spearfishing, carrying fish on belt',
 "Ship's boat capsized in squall, captain & 2 sailors clinging onto hull",
 'Copra vessel with 19 on board was wrecked in a squall',
 'Swimming after being swept into sea by a large wave',
 'Swimming / shipwreck',
 'Wading in school of baitfish',
 'Working on the bridge when he fell into the river',
 'Feeding a shark',
 'Fishing for white sharks',
 'Surfing & filming dolphins',
 'Freediving for trochus shell (submerged)',
 'Spearfishing, but swimming at surface',
 'Diving, feeding sharks',
 'Boogie boarding / wading',
 'Sight-seeing',
 'Lifeboat capsized',
 'On expedition filming a feature movie & standing on tripod',
 'Hand feeding sharks',
 'Standing ',
 'Wading / Surfing',
 'Diving, gathering shellfish',
 'Fell overboard from USS Ward',
 'Crossing the river mouth',
 'Fell oveboard from steamer Wanderer',
 'Dragging stranded shark into deeper water',
 'Scuba diving for abalone (at surface)',
 'Pearl diving, but standing in the water',
 'The Christie V sank on 11/6/1988, survivors were adrift on a dinghy',
 'Fishing for rock lobster',
 'Hunting seashells',
 'Fishing, sitting in stern of small boat, feet dangling in the water',
 'Spearfishing, free diving, possibly ascended into path of cruising shark',
 'Knocked into the water',
 'Attempting to chase shark out to sea',
 'Shipwrecked; adrift on raft for 2 days & 2 nights',
 'Bathing ',
 'Paddle-surfing',
 'Motor boat Rebel Belle lost',
 'Kiteboarding',
 'Swimming (using a float)',
 'Standing in knee-deep water',
 'On life raft tethered to lifeboat. A seaman put hand over side to rinse a cup',
 'On fishing boat & trailing hand in the water',
 'Diving for shells, saw shark circling wife near the surface, intercepted shark & it pulled him beneath the water',
 'Kayaking / Fishing',
 'Torpedoed & burning British  light cruiser with a crew of 450 men',
 'Fishing, lifting shark out of craypot',
 'Motor launch Baby Princesa capsized with 22 people on board',
 'Unknown',
 'Diving for trochus from lugger',
 "Fell off surfboard 20' from shore",
 'Jumped overboard to rescue companion',
 'Ditched plane in the sea & were adrift on a rubber life raft. ',
 'Sea Disaster, sinking of the  SS Vestris',
 'Ship Mariston torpedoed & sunk',
 'native boats sunk in storm',
 'Free diving / spearfishing, from paddleboard & floating on the surface',
 'The 168-ton Belmore foundered in heavy seas',
 'Spearfishing / swimming on surface',
 'Deserting the bark Nazarene',
 'Net fishing, fell into the water',
 'Jumped overboard',
 'Fishing, setting nets',
 '17 Maldivians adrift in open boat for 31 days',
 'ship M.V. Rizal sank during typhoon',
 'Swimming, towing a kayak',
 'Attempted to return injured shark to the sea',
 '90 European civilians, many women & children, were placed on the deck of a Japanese submarine that submerged when it was well offshore',
 'Swimming from camp',
 'Chasing shark out of bathing area while riding on a surf-ski',
 'Dog paddling or standing',
 'Jumped into the water',
 'Wade Fishing',
 'Standing, gathering oysters',
 'ship William Penn grounded & broke apart',
 'Searching for remains of  Dr. Marais',
 'Windsurfing (urinating on his board)',
 'Crew swimming alongside their anchored ship',
 'Tuna fishing, standing on stern platform that was submerged by waves',
 '3-masted steel barque Glenbank foundered during a cyclone',
 'Spearfishing, pulled sharkï¿½s tail',
 'Leaving the water',
 'Diving in tuna net',
 'Fishing from dinghy',
 'Fishing boat swamped in storm',
 'HBM Magpie foundered in a squall',
 'Swimming / escaping imprisonment ',
 'Wading to shore from his boat',
 'Adrift on a raft ',
 'Fishing, thrown into water by heavy sea, clinging to rocks at the water line',
 'Fishing from market fishboat Sea Spray',
 'Landing hooked shark in boat',
 'Wading / fishing & carrying a bag of fish',
 "Fishing, caught a 15' shark & took it onboard",
 'Spearfishing & diving for paua',
 'Fishing, hauling in a 5-lb snapper',
 'Rowing a dinghy',
 'Steinhart Aquarium',
 'Floating on back',
 'Swept out to sea while fishing',
 'Snorkeling, possibly holding a fish',
 'Air/Sea Disaster Pan-American Airlines Stratocruiser with 44 people onboard crashed into the sea',
 'Plane forced down, 3 men on rubber life raft. Put hand over side to feel drift of boat ',
 'Investigating shark sighting',
 'Fishing & spearfishing',
 'Washed overboard from the barque Mary Eady',
 'Removing shark from net',
 'Dynamiting fish',
 'Coming ashore on a hawser',
 'Plane crashed in water, men in life raft',
 'Diving off wharf',
 'Boat, with 42 passengers onboard, capsized in rough seas',
 'Attempting to retreive a dinghy',
 'boat capsized',
 'Diving for Abalone',
 'Fell overboard, hanging onto lifebuoy',
 '"Boat accident"',
 'Fishing, one of three fishermen swept into the sea by a large wave ',
 'Wading to shore after surfing',
 'Scuba Diving for scallops',
 'Riding floatation device',
 "Days before the surrender of Singapore, the 3 men escaped to Sumatra where they acquired a 17' dinghy. After 125 days at sea they drifted back to Sumatra",
 'Boogie boarding, kicked at object in the water',
 'Spearfishing, but standing in the water',
 'Capsized fishing boat',
 'Spearfishing, had fish on his spear',
 '3,909-ton Panamanian freighter Chieh Lee sank in a typhoon',
 'Two canoes with 14 aboard blown to sea in a storm. While adrift for 3 week, one person fell overboard and was killed by a shark',
 'Adrift on refugee raft',
 'Greek steamship Lakonia caught fire, 98 of her 646 passengers, and 30 of her crew of 376 perished',
 'Free diving for scallops',
 'Diving for trochus , but swimming on surface',
 'Diving for lobsters',
 'Conducting research',
 'Swimming near anchored ship',
 'Floating in inner tube',
 'Free diving for abalone (submerged)',
 'Pearl diving from lugger Whyalla',
 'Examining netted shark, that had been shot',
 'Playing soccer in the water',
 'Man fell overboard from ship. Those on board threw a rope to him with a wooden block & were pulling him to the ship',
 'Fishing, walking in river to cast',
 'Floating in creek',
 'Attacked shark with fists',
 '3 men & 2 boys picked up wearing life jackets and with inner tube',
 'USS Hoel DD 533 sunk on 10/24/1944 in the Battle off Samar. 2 crewmen were swimmng alongside a floater net &',
 'Fishing for the shark that killed George Lundberg',
 'Free diving, Spearfishing',
 'Petting captive sharks',
 "a corsair's boat was overturned",
 'Sea disaster, foundering of the cargo vessle M/V Dorolonda',
 'Dived from inner-tube',
 'Moving shark from tuna vessel when boat rolled, placing both man & shark in chest-deep water',
 'Diving for pearls',
 'Cleaning a tank',
 'Removing shark from a trap',
 'Fishing, holding fish in right hand',
 'Sea Disaster : Wreck of the Carrie E. Long',
 'Ditched aircraft, 3 men in the water. Swam for 31 hours',
 'Boat capsized, swimming ashore',
 'Swimming after boat became disabled',
 'Floating on an inflatable raft',
 'Collecting ornamental fish',
 'The World Liberty and the tanker Mosli collided. The  Halcyon Breeze sent a lifeboat to the rescue, but it was smashed, throwing 6 men in the  water.',
 'Kayaking',
 'Swimming, when caught in heavy seas',
 'Jerked overboard while pole fishing for tuna',
 'Free diving or wading back to shore',
 'Surfing / Wading',
 'H.M.S. Cornwall & H.M.S.Dorsetshire sunk by Japanese dive bombers. Officers & men in the water formed a circle with 60 of their dead in the center for 36 hours',
 'Diving?',
 'Attempting to attract dolphins',
 'Fell overboard from USS cruiser Tacoma',
 'Collecting aquarium specimens',
 'Harpooning turtles',
 'Spearfishing / free diving',
 'Wading to dinghy, carrying his son',
 'Chumming for sharks',
 'Diving, attempting to retrieve body of drowning victim wedged between rocks',
 'In deep water about 100 yards from his ship',
 'Holding shark on leader & dangling it above the water',
 'Hunting crayfish',
 'Dived overboard & was swimming near stern of trawler',
 'Hookah diving for abalone (submerged)',
 'Paddle-boarding',
 'Helmet diving in Miami Seaquarium',
 'Jumped overboard and swimming',
 'Sea Disaster, sinking of the motorship Wingate',
 'Carrying a supposedly dead shark by its mouth',
 'Fishing, boat capsized',
 'Chumming for white sharks',
 'Boat of a Hawaiian brig was stove in by  whale',
 'Fishing from launch, fell into net with shark',
 'Swimming, caught in strong backwash & disappeared',
 'Swimming in the channel',
 'Slipped off rocks and fell into the water',
 'Spearfishing / scuba diving',
 'Diving / Kissing the shark',
 'Swimming ashore after launch capsized',
 'Gaffing & attempting to bring onboard a harpooned shark',
 'Floating on a raft',
 'Boogie-boarding / swimming',
 'Treading water',
 'Diving around anchored liner',
 'Swimming off yacht',
 'Wading or swimming',
 'Oystering',
 'Defecating in water beneath the docks',
 'Fishing for trout ',
 'Free diving for trochus',
 'Unknown, their unoccupied yawlboat was recovered',
 'Working prawn net',
 'Clinging to overturned rowing boat',
 'Diving. Shark ï¿½swallowedï¿½ his hand, so he threw his other around the shark and went ï¿½shark-back ridingï¿½ for 30 yards until the shark opened its jaws',
 'Sailboarding, fell into water 100 yards outside the breakwater',
 'Fishing (Seining)',
 'Closed circuit diving (submerged). Diving to recover jettisoned packets of opium for police',
 'Walking on reef',
 'Treading for clams',
 'Jumping',
 'Spearfishing Competition',
 'Moving a shark in a net ',
 'Abandoning burning ship Captain George in raging seas',
 'Ferry boat Dona Paz with 4431 passengers exploded & caught fire when she collided with an  oil tanker ',
 'Sitting on side of dinghy mending a net',
 "Bathing in 5' of water",
 'Swimming ashore from fishing boat swamped and sunk by a squall',
 'American freighter Mormackite, bound from Buenos Aires for Baltimore, capsized & sank in heavy seas',
 'He was fighting a shark when his boat capsized & he disappeared',
 'Body boarding or surfing',
 "Fishing, standing in 2' of water",
 'Commercial spearfishing',
 'Feeding mullet to sharks',
 'Swimming near his boat',
 'Attempting to drive shark away from the beach',
 'Hunting seals',
 'Scuba diving',
 'Fishing ',
 'Playing in the surf',
 'Fishing boat',
 'Standing in waist-deep water, helping his father tend a gill net containing dead fish',
 'Sea disaster',
 'Sailing',
 'Fishing for cod',
 'Loss of the schooner Nomad',
 'Dived into the water',
 'Hard hat diving',
 'Surf fishing in waist-deep water',
 'Surfing, but lying prone on his board',
 'Fishing, hauling in net, shark in net',
 'Sea disaster : Wreck of the Taiaroa',
 'Sculling',
 'Shark fishing',
 'Fishing for sharks when he became entangled in net & fell overboard',
 'Climbing back on ship',
 'Crossing the bay at the ford',
 'Standing, watching seine netters',
 'Inflatable boat',
 'Ferry capsized',
 'Swimming with board',
 'Paddling',
 "Swimming at surface through school of feeding 2.5' to 5ï¿½ sharks",
 'Pacific Seafarer of US Navy',
 'Surf fishing, wading ',
 'Went over side of boat at trochus ground',
 'The USS Wahoo torpedoes & sank the Japanese troop transport Buyo Maru',
 'Kayaking or Wave skiing',
 'Body surfing or Boogie boarding',
 'Swimming with motor tube',
 'Attempting to rescue woman seized by shark',
 'Attempting to drag hooked shark ashore by its tail',
 'Standing in water with child in her arms',
 'Spearfishing/ filming',
 'Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days',
 'Dived from dinghy to retrieve oar in heavy seas',
 'Spearfishing, hunting crayfish',
 'Free diving for lobster',
 'Launching a boat',
 'Scuba diving, reportedly also spearfishing',
 'Fell overboard from P&O steamship Arabia',
 'A father bathing his smallest daughter when the shark bumped her out of his arms and carried her into deep water',
 'The 426-ton cargo ship Mia, laden with cement, capsized in heavy seas ',
 'Free diving for abalone (ascending)',
 'Diving (Helmet) for sponges',
 'Colombian  (Avianca) DC-4 airliner plunged into the sea 5 minutes after takeoff',
 'Surfing (or body boarding)',
 'The schooner Tahitienne foundered in a hurricane',
 'The steamships Thingvalla and Geiser collided',
 'Scuba Diving',
 'Free diving',
 'Swimming, after single-engine aircraft went down in the sea',
 'S.S. Marine Sulphur Queen, laden with molten sulphur was bound from Beaumont, Texas for Norfolk, VA, when she disappeared with 39 on board',
 'Lobstering',
 'Fishing with dynamite',
 'Fishing from shore',
 'Overturned skiff',
 'Fleet of canoes caught by a squall and charged by sharks.',
 'Swimming out to porpoises ',
 'Wreck of the schooner Driver',
 'Swimming to canoe',
 'Helping angler land a shark',
 'Shipwrecked Persian Fleet',
 'Canoe capsized by shark',
 'Diving for trochus',
 'Jumped overboard ',
 'Playing in surf with his child  (9)',
 'Hardhat diving',
 'Surfing, sitting on board',
 'Survived US Naval aircraft crash, climbing onboard rescue vessel when he fell back into sea ',
 'Diving for beche-de-mer from lugger',
 'Fishing / cleaning fish, dived into water to retrieve a lost fish',
 'Spearfishing with Scuba gear',
 'Swimming in section of river used for washing clothes & cooking utensils',
 'Freedom swimming',
 'Spearing a shark',
 'Fishing from surf ski',
 'Photographing the shark',
 'Swimming. Passer-by, Len Bedford, heard him shriek , saw shark leap from the water & swimmer disappeared',
 'Diving for trepang',
 'Swimming / Body surfing',
 'Washed off catamaran in the surf',
 'Night diving',
 'Hardhat diving ',
 "Fishing from 34' boat when pulled overboard by hooked shark",
 'Free diving, surveying a pipeline & examing cathodes under jetty',
 'boat from the Austrian ship Elizabeth',
 "Accidentally stood on hooked shark's tail before attempting to gut it ",
 'Swimming from naptha launch after a day of fishing',
 'Wading, knocked down & swept away by large waves',
 'Pulling raft out to ride to shore',
 'Crossing river on a raft',
 'Kite Surfing',
 'Fishing, Struck by another shark when removing shark from line',
 '14 m prawn trawler New Venture capsized  & sank in heavy seas Three people in the water',
 'Fishing schooner Jose Luis foundered',
 'Canoe capsized with 10 occupants, 8 survived,  Hamilton swam off to seek help',
 'Sponge diving',
 'Kneeling in the water',
 'Vessel caught fire & capsized, survivors in the water',
 'Cutter capsized',
 'Snorkeling ï¿½ hunting crayfish and abalone',
 'Wreck of the USS Somers',
 'Testing anti-shark cage',
 'Fishing (big game)',
 'On 6-Nov-1942, the German submarine U-68 sank the City of Cairo 5 days from Cape Town, survivors took to lifeboats & rafts. On the 15th day, a fireman jumped over the stern & was taken by sharks',
 'On December 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in Silcily and southern Italy, killing more than 100,000 people',
 "16' catamaran capsized previous night, occupants stayed with wreckage until morning, then attempted to swim ashore",
 'Spearfishing / Free diving',
 'Floating on inner tube raft',
 'Attempting to rescue a shark',
 'Spearfishing, but swimming on surface',
 'Attempting to rescue crew after whale upset their boat',
 'Hunting sharks',
 'Ocean racing',
 'Standing on his hands',
 'Swimming between  anchored  pearling luggers',
 'Tagging sharks',
 'Fishing for shrimp',
 'Speared a grouper, saw shark but it came for him instead of the fish so he fired spear into sharkï¿½s mouth. Then shark took grouper but unable to swallow because of the spear in its mouth.',
 'Wading, netting fish',
 'Swept off deck of S.S.Frontenac enroute from West Indies to US',
 'Fell into water while attempting to boat a swordfish',
 'Fishing, standing in water washing fish',
 'Jumped overboard from Norwegian steamship Venator',
 'Paddling a surfboat',
 'Hooking into a whale',
 'Dropping anchor',
 'He drowned when boat capsized',
 'Observing a shark feeding on a carcass of a humpback whale',
 'Resting on body board',
 'Swimming in waist-deep water ',
 'Went overboard',
 'Standing in inner tube',
 'Diving for crayfish',
 'Skindiving',
 'Free diving for crayfish',
 "Spearfishing, holding 5' speared fish",
 'Stand-Up Paddleboarding',
 'Swimming behind sailboat',
 'Kayaking ',
 'Snorkeling (filming the sardine run)',
 'Washed into sea while picking opihi',
 'Diving / fishing',
 'Jumped overboard to rescue a man',
 '"Crossing the river"',
 'Sitting',
 'Dived naked into the water on a bet',
 'Sinking of the dredge World Atlas',
 'Stuffing a shark into an automobile',
 'Floating, holding onto an oar after dory capsized',
 'Attempting to fix motor',
 'male',
 'Swimming /  boogie boarding',
 'Swimming near jetty',
 'Floating on inner tube after diving for lobster',
 'Crossing inlet in a boat, seen fighting sharks with his oar, sharks smashed boat',
 'Ferry boat sank',
 'Free diving, collecting shells',
 '"Climbing up to ship after repairing the stern in water"',
 'Scuba Diving for lobster (at surface)',
 'Fishing,  tarpon being chased by shark  leapt across his skiff, breaking it in half & Larkin became tangled in the net',
 'Spearfishing, shark grabbed his white t-shirt and towed him ',
 '"Swimming vigorously"',
 'British ship Macedon was thrown on her beam ends by a sudden squall',
 'Diving for pen shells',
 'Feeding prawns to captive sharks',
 'Measuring sharks',
 'Preparing to fish for jack-mackerel',
 'Swimming to shore after a squall  capsized their motorized shark fishing boat',
 'Sinking of the ferryboat      Don Juan',
 'Fishing for mackerel',
 'Fishing, fell in water & swimming strongly to shore',
 ' ',
 'Diving off pier & treading water',
 'Attempting to land a boat from the Hinemoa',
 'Washing clothes',
 'Diving off jetty',
 'Wading, when he stepped on the shark',
 'Sea Disaster, sinking of the fishing  launch Mavis',
 'Swimming alongside warship   Tsingt-ao',
 'Surfing amid a shoal of sharks',
 'Swimming, after falling off towed kneeboard',
 "Fishing - 'tag & release'",
 'On a float',
 'Hookah diving',
 'Collecting dynamited fish',
 'Restraining a beached shark',
 'Fell from wharf into water & attacked immediately',
 'Scuba diving ',
 'Swimming alongside the SS Kearsarge',
 'Washing his feet',
 'Fishing for albacore',
 'Fleeing across a river',
 'Fell oveboard',
 'Body-boarding',
 'Swimming, towing an empty barrel',
 'Rolled off raft',
 'Sponge divers',
 'Gaffing netted shark',
 'Hiking on the beach',
 "Lying on the bottom of a 16' dinghy",
 'Fishing, speared shark upset canoe & man fell in water',
 'Fishing for lobsters',
 'Riding horseback across the creek',
 'The shrimper Loless Maurine capsized in heavy seas & the men were swimming ashore  ',
 'Pearl diving from lugger',
 'Scuba diving (submerged)',
 'Setting crayfish pots',
 'Scuba diving & spearfishing',
 'Attempting to remove fishing net from submerged object',
 'Washed into sea while picking opihi & attacked by 2 large sharks ',

In [288]:
df.activity=df.activity.str.lower()
df.activity=[re.sub(r".*fishing.*|.*swimming.*|.*diving.*|.*surf.*|.*bathing.*|.*fell overvoard.*|.*filming.*|.*floating.*", "", str(x)) for x in df.activity]
df.activity=[re.sub(r".*wreck.*|.*sinking.*|.*boat.*|.*sea disaster.*|.*capsized.*|.*sank.*|.*collided.*|.*sunk.*", "boat wreck", str(x)) for x in df.activity]
df.activity=[re.sub(r".*dived.*", "diving", str(x)) for x in df.activity]
df.activity=[re.sub(r".*fell.*|.*jump.*", "fell/jumped into water", str(x)) for x in df.activity]
df.activity=[re.sub(r".*padling.*|.*rowing.*|.*sailing.*|.*canoeing.*|.*paddling.*|.*paddle.|.*yacht.*", "cruising", str(x)) for x in df.activity]
df.activity=[re.sub(r".*snorkeling.*", "swimming", str(x)) for x in df.activity]
df.activity=[re.sub(r".*adrift.*", "being adrift", str(x)) for x in df.activity]
df.activity=[re.sub(r".*air disaster.*|.*aircaft exploded.*|.*aircraft crashed.*|.*b-24.*|.*boeing.*", "air disaster", str(x)) for x in df.activity]
df.activity=[re.sub(r".*hunting.*|.*netting.*|.*killing.*|.*collecting.*", "fishing", str(x)) for x in df.activity]
df.activity=[re.sub(r".*standing.*|.*wading.*|.*walking.*", "standing/wading in water", str(x)) for x in df.activity]

In [289]:
# Se redujo a cerca de un cuarto de las actividades originales y se podrÃ­a continuar reduciendo
df.activity.nunique()

371

## Year

In [290]:
df.date.nunique()

5128

In [291]:
set(df.date.unique())

{'21-Sep-03',
 '16-Feb-46',
 '23-Apr-89',
 'Reported 21-Apr-1892',
 'May-68',
 '04-Sep-83',
 '27-Jul-80',
 'Reported      23-Aug-1998',
 '03-May-59',
 'Reported 18-Sep-2006',
 '22-Jul-11',
 '15-Nov-99',
 'Aug-92',
 '27-Feb-63',
 '23-Dec-34',
 '04-Jul-09',
 '07-May-00',
 '17-Aug-92',
 '04-Aug-61',
 '20-Jun-05',
 'Reported 11-Jan-1921',
 '30-Mar-71',
 'Reported    27-Mar-2005',
 '02-Jan-03',
 'Reported 24-Oct-1878',
 'Before 1936',
 'Sep-66',
 '1993',
 '28-Jul-63',
 '30-Sep-84',
 '13-Feb-82',
 ' 05-Nov-1997',
 '27-Feb-60',
 '1957',
 'Reported 26-Feb-1804',
 '23-Dec-92',
 '23-Jan-04',
 '25-Jan-48',
 '15-Sep-16',
 '22-Jun-1898',
 '05-Feb-70',
 '12-Aug-59',
 'Jan-91',
 '15-Jul-02',
 '15-Apr-14',
 '19-Feb-51',
 'Reported 25-Jul-1905',
 'Reported 15-Nov-1921',
 '1642',
 '06-Feb-67',
 '08-Jul-26',
 '24-May-50',
 '16-Nov-06',
 '08-Oct-15',
 'Jul-00',
 '28-Apr-10',
 '14-Jul-96',
 '1949',
 '04-Oct-15',
 '15-Dec-07',
 '24-Dec-02',
 '06-May-72',
 'Dec-00',
 '28-Jul-95',
 '28-Dec-92',
 'Reported 28-Oct-2010',
 '09-Feb-96',
 '15-Dec-98',
 '19-May-81',
 '16-Nov-14',
 '03-Oct-86',
 '29-Aug-15',
 '10-Mar-83',
 '09-Sep-73',
 '03-Aug-01',
 '12-Nov-89',
 ' 19-Feb-2016',
 '18-Feb-68',
 '26-May-95',
 'Nov- or Dec-1873',
 'Sep-59',
 '07-May-03',
 '19-Oct-81',
 '20-Aug-56',
 'Ca. 1840',
 '13-Feb-88',
 'Reported 16-Sep-1998',
 '27-Jun-16',
 '17-May-09',
 'Reported 28-Feb-2011',
 '23-Dec-11',
 '19-Jun-99',
 '04-Jan-84',
 '20-Jul-81',
 '07-Feb-60',
 '26-Mar-16',
 'Ca. 1960',
 'Feb-69',
 'Reported 17-Nov-2014',
 'Reported 10-Oct-1906',
 '10-Feb-75',
 '1880-1899',
 '19-Aug-77',
 '13-Apr-16',
 'Early summer 1960',
 '12-Mar-29',
 '14-Feb-00',
 '05-Feb-16',
 '31-Aug-01',
 'Jan-09',
 '12-Nov-42',
 '09-Feb-13',
 '24-Oct-97',
 '01-Sep-37',
 '16-Aug-73',
 '31-Mar-12',
 '23-Jul-15',
 '1923',
 'Aug-62',
 'Reported 1638',
 '06-Apr-71',
 '25-Jul-10',
 '1913',
 '1887',
 '26-Dec-63',
 '16-Feb-32',
 '23-Apr-11',
 '20-Mar-07',
 'Reported 07-May-1952',
 '12-May-09',
 '07-Oct-06',
 '13-Sep-14',
 'Feb-62',
 ' 15-Feb-1988',
 '09-Jun-99',
 '24-Aug-81',
 '09-Feb-75',
 '17-Jan-59',
 '26-Sep-61',
 '13-Jan-49',
 'Reported 03-Mar-2016',
 '29-Mar-14',
 '26-Jul-96',
 '08-Jul-90',
 '03-Apr-94',
 '27-Jun-13',
 '05-Oct-38',
 '26-Mar-1703',
 '22-Jun-66',
 '08-Jan-83',
 '15-May-05',
 'Reported 14-Jul-1932',
 '19-Jan-75',
 '01-Apr-02',
 '05-Sep-02',
 '25-Nov-1880',
 '28-Oct-97',
 '31-Jul-24',
 '28-Apr-01',
 '06-Sep-12',
 'Reported 13-Jul-1888',
 '07-Feb-81',
 '28-Nov-90',
 '06-Jan-87',
 '29-Aug-10',
 'Oct-67',
 '12-Aug-07',
 '27-Oct-80',
 '11-Sep-00',
 'Reportd 15-Jul-1894',
 '17-Oct-14',
 '02-Jun-02',
 'Reported 04-Aug-1936',
 '26-Jun-77',
 '12-Apr-15',
 '04-Apr-14',
 '01-Sep-67',
 '02-Jun-66',
 '11-Aug-96',
 '04-Nov-86',
 '08-Apr-30',
 '18-Apr-02',
 '29-Oct-14',
 '11-Nov-1855',
 '23-May-81',
 '11-Sep-06',
 '30-Mar-61',
 '10-Jul-07',
 'Reported 06-Sep-1961',
 '19-Jul-2007.a',
 'Reported 27-Jan-2009',
 '06-Sep-61',
 '22-Sep-84',
 '08-May-55',
 'Reported 19-Dec-1940',
 '28-Mar-1855',
 '18-Dec-95',
 '03-Apr-09',
 '12-Jan-39',
 '1853',
 'Reported 03-Sep-1951',
 '11-Jul-28',
 'Apr-52',
 '22-May-16',
 '22-Aug-95',
 '23-Jan-07',
 '17-Jun-58',
 '14-Apr-06',
 'Early Jun-2000',
 '13-Feb-10',
 '26-Jul-74',
 '01-Nov-44',
 '09-Jan-24',
 '25-Sep-12',
 '13-Feb-06',
 '12-Mar-25',
 'Before 1962',
 '07-Jul-95',
 '20-Jun-32',
 'Reported 17-Aug-1890',
 '07-Jul-14',
 '21-Aug-05',
 '10-Mar-82',
 '13-Feb-11',
 '27-Oct-56',
 '03-Apr-14',
 '11-Aug-12',
 '22-Sep-48',
 '08-Aug-1878',
 '10-Dec-65',
 '16-Oct-65',
 '20-Feb-12',
 '24-Mar-79',
 '11-Apr-99',
 '06-Dec-06',
 '01-Oct-11',
 '24-Jan-46',
 '12-Nov-49',
 '12-Dec-58',
 '03-Jan-61',
 '05-Jan-56',
 '30-Aug-55',
 'Jan-41',
 '14-Sep-93',
 '30-Apr-61',
 '05-Oct-02',
 '17-Oct-67',
 '1920s',
 '07-Nov-07',
 '24-Sep-12',
 '29-Oct-00',
 'Mar-68',
 '02-Jan-12',
 '21-Sep-17',
 '1758',
 '03-Jun-89',
 '15-Jan-80',
 'Jun-41',
 '30-Jul-04',
 '1949-1950',
 'Jul-43',
 '10-Jun-72',
 '14-Jun-15',
 'Reported 03-Jul-1962',
 '21-Jul-12',
 '10-Mar-03',
 '17-Feb-90',
 '23-Mar-70',
 'Reported 25-Mar-1935',
 '1827',
 '20-Aug-07',
 '07-Jan-74',
 '1749',
 '06-Jan-88',
 'Apr-44',
 '01-Jan-1886',
 '02-Jan-95',
 '06-Mar-12',
 '30-Nov-12',
 'Reported 05-May-1917',
 '01-Feb-10',
 '17-Jul-07',
 '02-Jun-00',
 '06-Jun-77',
 'Reported 26-Sep-1914',
 '16-Dec-13',
 '07-Dec-41',
 '22-Feb-12',
 '30-Nov-10',
 '16-May-12',
 '10-Dec-64',
 '09-Mar-05',
 '23-Feb-06',
 '25-Jan-59',
 '07-Jul-36',
 '19-Jun-79',
 '26-Jul-75',
 ' 14-Aug-2013',
 '05-Feb-07',
 '31-Aug-95',
 '19-May-60',
 '18-Sep-92',
 '19-Aug-62',
 '02-Mar-1892',
 'Apr-1978`',
 'Reported 14-Jun-2009',
 'Reported 22-Dec-1887',
 '01-May-11',
 '23-Jun-29',
 '04-Jun-42',
 '16-Jun-23',
 '06-Jun-89',
 '22-Apr-14',
 '20-Mar-22',
 '02-Jan-62',
 '25-Sep-00',
 '02-Jul-59',
 '29-Jan-66',
 'Reported 27-Jan-1864',
 '25-Jan-13',
 '17-Jul-16',
 'Ca. 1890',
 '03-Nov-15',
 '29-Apr-68',
 '12-Oct-90',
 '14-Dec-62',
 '14-Nov-47',
 '28-Jun-91',
 '10-Aug-19',
 'Reported 01-May-1911',
 '13-Sep-87',
 '21-Nov-05',
 '20-Apr-02',
 'Reported 21-Aug-1941',
 '13-Jun-70',
 'Reported 15-Jul-1914',
 '30-Apr-58',
 '15-Sep-48',
 '01-Aug-14',
 '14-Apr-90',
 '21-Jul-1889',
 'May-55',
 '08-Feb-1887',
 '15-May-86',
 '12-May-12',
 '22-Nov-11',
 '08-Oct-08',
 'Reported 01-Aug-1978',
 '13-Apr-1898',
 '20-Aug-15',
 '18-Feb-44',
 '28-Nov-02',
 '06-Jul-1842',
 '25-Apr-08',
 '1842',
 '15-Jan-61',
 '04-Jan-22',
 '16-Aug-74',
 '13-May-14',
 '06-May-22',
 '05-Apr-75',
 '23-Feb-75',
 '11-Jul-63',
 '11-Apr-09',
 '1937',
 '13-May-00',
 '1896',
 '18-Mar-23',
 '28-Jun-32',
 '07-May-56',
 '08-Apr-66',
 '04-Jul-75',
 '09-Jul-53',
 '20-Feb-83',
 '04-Aug-01',
 '20-Dec-05',
 '08-Feb-06',
 '05-Jan-47',
 '16-Mar-1877',
 '28-Apr-57',
 '16-Jun-47',
 '14-Sep-98',
 'Apr-46',
 '09-May-67',
 '30-Jan-94',
 '1923-1924',
 '12-Feb-16',
 '17-Feb-84',
 'Jul-50',
 'Reported 28-Jan-1922',
 '09-Jan-73',
 '07-Apr-26',
 'Mar-73',
 '10-Jul-02',
 'Reported 04-Jun-1876',
 '1965',
 'Reported 05-Nov-1963',
 '20-Oct-56',
 '01-Jul-48',
 '16-Mar-72',
 '25-Mar-08',
 '04-Sep-07',
 '22-Jul-15',
 '02-Nov-02',
 '1996',
 'Reported 22-Jun-1893',
 '08-Mar-20',
 '20-Mar-35',
 '05-Feb-64',
 '18-Jan-12',
 '05-Jan-13',
 '18-Jul-91',
 '25-May-15',
 '31-Mar-98',
 'Ca. 1881',
 '13-Sep-89',
 '25-Dec-73',
 'Jan-59',
 '19-Aug-03',
 '09-Jan-91',
 '25-Jul-1862',
 '1897',
 '   21-Sep-1908',
 '05-Sep-15',
 '27-Sep-81',
 '16-Dec-09',
 '11-May-1870',
 '31-Jul-15',
 '12-Dec-78',
 '24-Nov-73',
 '31-May-44',
 '26-Feb-01',
 '27-Jan-32',
 'Reported 20-Sep-1953',
 '24-May-96',
 'Reported 21-Jun-1896',
 '12-Oct-08',
 'Feb-77',
 'Apr-98',
 '22-Nov-25',
 '04-Feb-96',
 '12-Mar-61',
 '15-Jun-11',
 '29-May-19',
 '28-Jul-52',
 '12-Jul-97',
 '09-Jan- 1874',
 '28-Nov-59',
 'Ca. Nov-1826',
 '09-Dec-1895',
 '05-Aug-97',
 '23-Nov-47',
 '24-Oct-57',
 '09-Feb-92',
 'Reported 28-Oct-1995',
 '04-Jan-06',
 '09-Oct-94',
 '12-Sep-37',
 '04-Jun-30',
 '26-Dec-59',
 '06-Jan-62',
 '01-Feb-64',
 '15-Dec-1877',
 'Reported 17-Mar-2009',
 '22-Mar-31',
 'Reported 16-Nov-1963',
 'Before 1927',
 '10-Jul-03',
 '31-Mar-13',
 'Aug-69',
 '15-Feb-62',
 '  Reported 31-Jul-1958',
 '  25-Jun-1982',
 '10-Nov-02',
 'Aug-93',
 '13-Mar-75',
 'Reported 17-Feb-1964',
 '19-Jul-13',
 'Reported 08-Jul-1819',
 '31-Dec-77',
 '28-Jun-46',
 'Reported 14-Jun-1890',
 '29-Aug-09',
 '27-Oct-76',
 '1852',
 '03-Oct-02',
 '14-Aug-02',
 '22-Mar-83',
 '28-Jun-98',
 '15-Aug-07',
 '05-Jan-57',
 '26-Jul-1975.b',
 '02-Oct-00',
 '15-Jul-63',
 '15-Feb-08',
 '05-Aug-77',
 '13-Sep-02',
 'Reported 21-Feb-2008',
 '13-Aug-06',
 '08-Jun-14',
 '1982',
 'Before 1906',
 '02-Dec-89',
 '02-Feb-64',
 '25-Aug-01',
 '26-Aug-07',
 '04-Apr-70',
 '01-Oct-99',
 'Jul-67',
 '04-Sep-25',
 '14-Oct-03',
 'No date, Before May-1996',
 '30-Dec-12',
 '06-Jan-63',
 '08-Oct-13',
 'Before 1903',
 '03-Feb-20',
 'Before 2004',
 '22-Jan-10',
 '1975',
 '18-Jun-24',
 'Ca. 1554',
 '31-May-09',
 '26-Aug-67',
 '27-Mar-09',
 'Summer 1950',
 'Dec-1826',
 '10-Jul-58',
 '21-Apr-09',
 '21-May-13',
 '16-Apr-32',
 '13-Jan-15',
 '17-Oct-09',
 'Oct-86',
 '03-Feb-60',
 '11-Apr-29',
 'Apr-13',
 'Reported 01-Sep-1894',
 '10-Jan-96',
 '05-Oct-03',
 '13-Aug-35',
 '11-Dec-06',
 '22-Jul-41',
 'Reported 03-Feb-1930',
 '22-Sep-60',
 '14-Apr-1839',
 '25-Jan-66',
 '14-Mar-93',
 '24-Sep-00',
 '18-Jun-35',
 '25-Jan-24',
 '2000',
 '29-Dec-14',
 '11-Nov-85',
 'Reported 11-Jan-1827',
 '1779',
 'Reported 10-Aug-1949',
 'Reported 25-Aug-2014',
 '14-Apr-28',
 '25-Mar-88',
 '27-Jun-20',
 '12-Aug-00',
 '15-Apr-08',
 '27-Aug-34',
 '08-Jan-62',
 '28-Mar-60',
 '18-Oct-14',
 '1899',
 '02-Jan-16',
 '21-Sep-02',
 'Reported 21-Nov-1895',
 '27-Dec-00',
 '27-Jul-35',
 '25-Nov-05',
 '03-Nov-90',
 'Jun-53',
 'Reported 27-Jul-1947',
 '19-Jul-08',
 '21-Jul-97',
 '18-Oct-1887',
 '27-Aug-67',
 '11-Dec-54',
 '25-Dec-13',
 '02-Jul-60',
 '09-Aug-75',
 '27-Mar-1841',
 '20-Nov-33',
 '03-Nov-65',
 '02-Jul-77',
 '11-Dec-21',
 '06-Dec-51',
 'Jul-86',
 '12-Mar-36',
 '30-Jul-08',
 '26-Feb-68',
 '15-Jan-40',
 '02-Jan-93',
 '02-Nov-05',
 '25-Apr-03',
 '29-Sep-06',
 'Reported 1776',
 '15-Jan-11',
 '1919',
 '09-Sep-17',
 '06-Apr-09',
 '01-Jun-71',
 '09-Apr-03',
 '27-Jan-23',
 '23-Nov-76',
 '1960',
 '04-Feb-36',
 '15-May-14',
 '23-Jul-80',
 '06-Nov-00',
 '05-Mar-73',
 '29-Oct-07',
 'Reported 26-Jul-1898',
 '23-Jul-16',
 '28-Jul-1855',
 '06-Sep-97',
 '14-Feb-82',
 '17-Apr-63',
 '23-May-94',
 '12-Aug-03',
 'Before 1911',
 '17-Jun-62',
 '13-Feb-37',
 '05-Jul-75',
 '1836.07.26.R',
 'Reported 30-Jan-1893',
 '09-Jul-57',
 '25-Dec-15',
 '22-Aug-60',
 '17-Feb-82',
 'Reported 15-Dec-1877',
 '08-Jul-83',
 '31-May-83',
 '21-Jun-57',
 '07-Jul-91',
 '19-Sep-11',
 ' 27-Mar-2010',
 '23-Jan-06',
 '15-Aug-1899',
 '15-Jun-75',
 'Jul-87',
 '15-Mar-00',
 '26-Feb-12',
 '12-Jan-96',
 'Reported 27-Aug-2000',
 '31-Dec-03',
 '20-Oct-14',
 '11-Jan-76',
 '15-Sep-90',
 '26-Dec-48',
 '11-Jul-08',
 'Reported 30-Dec-1913',
 '02-Sep-62',
 '29-May-27',
 '28-May-65',
 '20-Jun-12',
 '01-Mar-50',
 '11-Nov-02',
 '01-Sep-16',
 '24-Jul-57',
 '12-Jul-56',
 '14-Jun-95',
 '04-Sep-15',
 '08-Nov-57',
 '29-Jul-05',
 '30-Nov-81',
 '2003?',
 '22-Jun-05',
 '24-Jan-01',
 '24-Apr-91',
 '26-May-38',
 '06-Sep-96',
 '22-Oct-88',
 'Reported 26-Sep-t937',
 '02-Jun-04',
 '23-Feb-98',
 '13-Feb-24',
 '22-Aug-88',
 '01-Dec-01',
 '25-Jan-61',
 '01-Dec-10',
 '31-Oct-04',
 '11-Oct-32',
 'Reported 03-Dec-2010',
 'Feb-55',
 '1941',
 '21-Dec-28',
 '24-Jan-95',
 '05-Jun-89',
 '1973',
 '01-Jan-81',
 '12-Jul-26',
 '05-Sep-00',
 'Mid Aug-1966',
 '1950 - 1951',
 '04-May-01',
 'Late Jul-1980',
 '28-Mar-1885',
 '02-May-06',
 '21-Mar-14',
 '07-Nov-75',
 '25-Sep-71',
 ' 13-Aug-2013',
 '23-Apr-57',
 '21-Jul-99',
 '27-Jul-16',
 '31-Jan-10',
 '20-Aug-04',
 '02-Sep-48',
 'Sep-98',
 '18-Jul-38',
 'Reported 07-Mar-1930',
 '14-May-14',
 '17-Jun-1886',
 '31-May-94',
 'Ca. 1911',
 '11-Aug-00',
 '18-Nov-89',
 'Reported 30-Dec-1919',
 '27-Jan-64',
 'Reported 26-Feb-1883',
 '17-Aug-72',
 '08-Nov-14',
 '14-Oct-89',
 '14-Aug-60',
 '12-Apr-09',
 '26-Dec-99',
 '21-Jul-14',
 '20-Jul-02',
 '10-Sep-66',
 'Mar-34',
 '20-Jan-44',
 '11-Feb-37',
 '25-Nov-41',
 '22-Nov-89',
 'Reported 30-Aug-1879',
 '18-Aug-92',
 '23-Jul-12',
 '18-Dec-57',
 '28-Jun-56',
 '11-May-01',
 '25-Aug-60',
 '22-Jan-64',
 '12-Oct-27',
 '29-Jan-99',
 '14-Mar-44',
 '01-Sep-29',
 '26-Aug-98',
 '15-Jul-13',
 '19-Aug-48',
 'Aug-43',
 '05-May-1862',
 'Reported 29-Oct-1926',
 '08-Sep-12',
 '1886',
 '03-May-79',
 '24-Jul-82',
 '23-Oct-26',
 '    10-Jan-2009',
 '28-Jan-1886',
 'May-Jun-1965',
 '07-Jan-62',
 '11-Mar-79',
 '24-Jun-15',
 '22-Jan-67',
 '15-Oct-90',
 'Reported 02-April 1906',
 '13-Jun-82',
 '03-Jun-17',
 '20-Aug-85',
 '27-Jul-78',
 '14-May-03',
 '29-Oct-05',
 '14-Jan-1884',
 '27-Jul-05',
 '20-Apr-97',
 '23-Jul-96',
 'Reported 09-Dec-1932',
 '04-Jan-1877',
 '12-Jul-16',
 'Reported 06-Sep-2010',
 'Reported 10-Sep-1973',
 '20-Mar-40',
 'Sep-03',
 '23-Sep-56',
 '02-Dec-99',
 '01-Jan-60',
 '1879',
 '01-Jun-61',
 '20-Oct-10',
 '22-Jan-04',
 '19-May-35',
 'Before 1996',
 '08-Apr-63',
 '13-Jun-15',
 'Early Sep-2000',
 '26-Oct-93',
 '19-Feb-58',
 'Late 1600s Reported 1728',
 '24-Jun-07',
 '10-Nov-59',
 '23-Oct-13',
 '03-Feb-10',
 '01-May-14',
 '29-Jan-08',
 'Before 1901',
 '11-Aug--2011',
 '04-Aug-97',
 '09-Nov-97',
 '01-May-10',
 '05-Mar-99',
 '08-Feb-03',
 'Reported 24-Dec-1946',
 '24-Sep-61',
 '22-Dec-98',
 '31-May-16',
 'Reported 06-Jul-1912',
 '12-Mar-76',
 '21-Aug-60',
 'Reported      13-Apr-2007',
 '23-Feb-02',
 '12-Jul-13',
 '22-Aug-21',
 '22-Oct-08',
 'Jun-75',
 'Oct-88',
 '01-Apr-60',
 'Some time between Apr & Nov-1944',
 '03-Sep-25',
 '13-Jan-12',
 '06-Jun-23',
 '25-Jul-49',
 '16-Jul-14',
 '22-Nov-13',
 '12-Sep-19',
 '19-May-91',
 '26-May-97',
 'Apr-70',
 '31-Dec-72',
 '22-Sep-98',
 '05-Aug-78',
 '10-Oct-1880',
 '12-Nov-93',
 '05-Apr-59',
 '20-Dec-87',
 'Before 1909',
 '03-May-01',
 '14-Jan-63',
 '19-Jun-03',
 '15-Jul-00',
 '02-Sep-53',
 '02-Sep-09',
 '05-Nov-69',
 '26-Feb-77',
 '09-Feb-27',
 '15-Nov-16',
 '08-May-45',
 '12-Jul-83',
 '20-Mar-67',
 '20-Sep-55',
 'Before 2016',
 '21-Dec-73',
 '14-Oct-72',
 '31-Jan-11',
 '01-Feb-58',
 '19-Jul-22',
 '05-Sep-70',
 '28-Mar-80',
 'Ca. mid-1870s',
 '07-Mar-61',
 '13-Oct-07',
 '10-Jul-15',
 '31-Oct-64',
 '29-Jun-83',
 'Reported 24-Oct-1888, but took place around 1868',
 '05-Sep-94',
 'Summer 1943',
 '22-May-92',
 'No date, Before Aug-1989',
 'Mar-00',
 'Feb-23',
 '03-Dec-00',
 '05-Oct-59',
 '09-Mar-69',
 '21-Sep-13',
 '27-Mar-04',
 '27-Oct-90',
 'Reported 25-Nov-1856',
 '14-Mar-43',
 'Jul-84',
 '11-Jul-88',
 '19-Feb-81',
 'Reported 06-Jun-1961',
 '25-Jul-1864',
 '20-Apr-63',
 '10-Jan-08',
 '02-Mar-1943 to 07-Mar-1943',
 'Ca. 5 A.D.',
 '31-May-12',
 '28-Mar-08',
 '09-Jul-02',
 'Reported 14-Feb-1975',
 '20-May-66',
 'Aug-66',
 '19-Sep-03',
 '13-Jun-33',
 'Reported 24-May-1944',
 '28-Jul-06',
 '31-Aug-12',
 '07-Sep-74',
 '23-Dec-57',
 'Reported 09-May 1927',
 '11-Nov-09',
 '09-Oct-10',
 '02-Sep-74',
 '25-Jun-05',
 '20-Jun-83',
 '26-Feb-1852',
 'Reported 26-Jan-2009',
 '04-Aug-75',
 '29-Mar-15',
 'Reported 24-Jul-2009',
 '06-Sep-14',
 '05-Jun-06',
 'Ca. 1915',
 'Between 18 & 22-Dec 1944',
 '14-May-1876',
 '17-Jan-85',
 'Reported 15-Apr-1893',
 '06-Jul-16',
 '21-Jul-92',
 '11-Feb-64',
 '20-Oct-13',
 'Oct-96',
 '19-Dec-65',
 'Reported 06-Apr-1738',
 '27-May-13',
 '21-Feb-97',
 'Aug-36',
 '06-Jan-12',
 '28-Jan-16',
 'Reported 04-Dec-1914',
 '15-Feb-53',
 '08-May-13',
 '08-Jul-12',
 'World War II',
 '21-Nov-24',
 '10-Mar-15',
 '30-Aug-91',
 '26-Jul-56',
 '14-Aug-59',
 '28-Apr-08',
 '29-Nov-29',
 '03-Jan-12',
 'Reported 23-May-1893',
 '17-Nov-95',
 '05-Jan-29',
 '02-Dec-75',
 '10-Dec-48',
 'Reported 22-Aug-1867',
 '1974',
 'Reported 10-Sep-1845',
 '31-Oct-32',
 '21-Mar-08',
 'Sep-44',
 'Reported 17-Jul-2013',
 '12-Aug-01',
 '22-Oct-10',
 '09-Mar-47',
 '20-Aug-61',
 '12-Jan-59',
 '27-Jul-04',
 '13-Apr-10',
 '04-Jan-02',
 '23-Mar-11',
 '11-Sep-92',
 '29-May-99',
 '15-Jul-31',
 '06-Aug-12',
 '01-Jul-81',
 '13-Feb-74',
 'Summer of 1959',
 '17-Jun-06',
 '21-May-02',
 '19-Jun-00',
 '26-Dec-42',
 '17-Jul-88',
 '14-Oct-69',
 '19-Jul-12',
 '12-Jan-86',
 '04-May-06',
 '14-Jan-05',
 '13-Dec-1884',
 '26-Jul-16',
 'Reported 06-Feb-2010',
 '02-Apr-02',
 ...}

In [292]:
df.date=df.date.str.lower()
df.date=df.date.str.replace("a few years before 1938", "1938")
df.date=[re.sub(r"no date, before |between|between   |reported |no date, before |before |circa |beforer |early |         |   |\?|reported ", "", str(x)) for x in df.date]
df.date=[re.sub(r"ca. |late| aug-1951 &  |during the war|summer of |mar-1943 to |letter dated| reported| 18 & |sep-1942 to |^ *", "", str(x)) for x in df.date]
df.date=[re.sub(r'summer |decp|1990 or |nov- or|may & |mar-1925 or |jul- to |mid |nov-1909 to |anniversary day" jan-1850 or ', "", str(x)) for x in df.date]
df.date=[re.sub(r' \(same day as  1954.00.00.f\)|reportd |1950 - |1920 -', "", str(x)) for x in df.date]
df.date=[re.sub(r"no date.*|.*b.b..*", "nan", str(x)) for x in df.date]

In [293]:
#para simplificar tomarÃ© sÃ³lo mes y aÃ±o de fechas
df.date=[re.sub(r"\d\d-", "", str(x)) for x in df.date]

#para estar seguro del aÃ±o se usa la columna year para pegÃ¡reselo a las fechas en los caso en que aplique
df['date_formato'] = [re.search(r"\w{3}-\d{2}$", str(x))!=None for x in df.date]
nueva_date=[]
for i in range(0, len(df.date)):
    if df['date_formato'][i]==True:
        nueva_date.append(re.sub(r"\d\d$","", df['date'][i])+str(df['year'][i]))
    else:
        nueva_date.append(df['date'][i])
df['date']=nueva_date

In [294]:
df.drop(columns=['date_formato', 'original_order'], inplace=True)

In [295]:
df[df.date=="jun-1886"]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href
5507,1886.06.17,jun-1886,1886,Unprovoked,australia,Queensland,Off Bribie Heads,,Lacoon,M,18,FATAL,Y,NaN,NaN,"Brisbane Courier, 6/21/1886",1886.06.17-Lacoon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5508,1886.06.02,jun-1886,1886,Invalid,usa,Hawaii,"Hamakua Homakua, Hawai'i",,2 women,F,NaN,The body of one woman had been bitten by a sha...,Y,NaN,NaN,G. H. Balazs & A. H. Kam; V.M. Coppleson (1958...,1886.06.02-Hamakua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [296]:
# las fechas que solo son aÃ±o le agregamos junio como mes
df.date=[re.sub(r"\d\d-", "", str(x)) for x in df.date]
df['date_formato'] = [re.search(r"^\d{4}$", str(x))!=None for x in df.date]

for x in range(0,len(df.date)):
    if df['date_formato'][x]==True:
        df["date"][x]="jun-"+str(df.date[x])

<ipython-input-296-d51b4bffa940>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date"][x]="jun-"+str(df.date[x])

In [297]:
# ya no se necesita 'date_formato', asÃ­ que se tira
df.drop(columns=['date_formato'], inplace=True)

## Fatal

In [298]:

df['fatal_(y/n)'].unique()
df['fatal_(y/n)']=df['fatal_(y/n)'].str.lower()
df['fatal_(y/n)']=df['fatal_(y/n)'].replace(' n', "n").replace('n ', 'n')

In [299]:
df['fatal_(y/n)'].unique()

array(['n', 'y', nan, 'unknown', 'f', '#value!'], dtype=object)

In [300]:
df.loc[(df['fatal_(y/n)'] =="f")|(df['fatal_(y/n)'] =="unknown")|(df['fatal_(y/n)'] =='#value!')] = "nan"
df['fatal_(y/n)']=df['fatal_(y/n)'].replace('n', False).replace('y', True)
df['fatal_(y/n)'] = df['fatal_(y/n)'].astype('bool')
df.rename(columns={'fatal_(y/n)':'fatal'}, inplace=True)

In [301]:
df['fatal'].unique()

array([False,  True])

## Name

In [302]:
df.name=df.name.str.lower()
df.name=df.name.replace("male", "").replace("male x 2", "").replace("5 men", "").replace("m.a.", "").replace("female", "")
df.name=df.name.replace("2 women", "")
set(df.name.unique())

{'',
 nan,
 'mark quirt',
 'brandon taylor',
 'stanley roser',
 'an elementary school teacher',
 'len jones',
 'walter c. german',
 'mikado nakamura',
 'jean-luc majele',
 'manning samuels',
 'porfirio lugo camacho ',
 'arthur e. taylor, a navy diver & member+g1053 of a 24-man demolition team',
 'toby',
 'charlie gauzer',
 'joseph friedlander',
 'occupant: hasan olta',
 'verenia keet',
 'mathieu dasnois',
 'daniel webb',
 'leo clarke',
 'ernest macdonald',
 'rescue boat of the glenelg surf club, captained by g.w. scarfe',
 'quassa, a torres strait islander',
 'taylor trumbauer',
 'erika hailey',
 'noel yates',
 'a native fisherman',
 'ernest tomson',
 'percy neale',
 'somali boatman',
 'cheryl teague',
 'andrew morris',
 'jordon garosalo',
 'tarara, a male',
 'jake poland',
 "21' boat sank. occupants: max butcher, george hardy & peter thorne",
 'hans vegsund',
 'hendrie nkwazi',
 'dave manson',
 'christian fairbourne',
 'josia mcspadden',
 'bruno giraud ',
 'rob bennett',
 'ramon cordoba',
 'lyudmila stolyarova ',
 'occupants of skin boats',
 'nahalehau',
 'michelle glenn',
 'tony johnson',
 'martin kane',
 'larry peebles',
 'philip light',
 'john saenza',
 'philip dorn',
 'jemmy',
 'speros gigis',
 'mr. ristow',
 'a male from waikato',
 'john campbell',
 '3 japanese divers',
 'a boy, one of the crew of the ship thomas gelston',
 'alfred haen',
 'robert clark',
 'farejallah',
 'stanley fisher',
 'bry & david mossman & 2 friends',
 'gilbert s. hotta',
 'yee wing ping (male)',
 'japanese female',
 'mr. l. e. brasting',
 "19' clinker-built craft. occupants: ray peckham & mr. l.c. wells",
 'i. padden',
 'jorge garcia',
 'scott stephens',
 'susan buecher',
 'david kohler',
 'bethany edmund',
 'mark rudy',
 'trevor burger',
 'noel buxton redfern',
 'richard tebutt',
 'chance dean',
 'e.c.p, a u.s. marine',
 'karl pollerer & eric eisesenid',
 'dr. alfred l. wilkes ',
 'waade madigan and dr seyong kim ',
 'albert mainlander, an aboriginal',
 'herbert webster',
 'allan green',
 'mary locklear',
 'm. schweitzer',
 'jonathan beard',
 'brandon chapman',
 'boat, occupants:  andrew peterson & peter jergerson',
 'william munich',
 'jean-michel pothin',
 'j.l.',
 'andy austin',
 'albert thomas burless',
 'open boat, occupants: robert ruark, hoyle dosher & elmer adkins',
 'kameron brown',
 'quinn gates',
 'kayak: occupant kelly janse van rensburg',
 'teresa cartwright',
 'paulo fernandes alves ferreira',
 'william stannard',
 'african slaves',
 'renate seiffert',
 'a deserter from the ship evarest',
 'john p. martin ',
 'j. wolffe',
 'thomas harrington',
 'andres puma (or pruna)',
 'oliver schorebreak',
 ' grace darling',
 '5.75 m wooden boat, occupant: yoshaiaki ueda',
 'peter ferrer',
 'claremont l. staden',
 'mrs. coe',
 'laurent chardard ',
 'kor van helden',
 'terrance gibson',
 'adolph crouse',
 'jason whitworth',
 'jean rene mathelon',
 'sam boger',
 'morris m. vorenberg',
 'santiago kapriel',
 'most were women & children',
 'darren harrity',
 '2 czech tourists',
 'josh green',
 'hana',
 't.j. nimmons',
 'kyra bandy',
 'vince wilson',
 'william charles beitz',
 'glen orgias',
 'benjamin brown',
 'mrs. burman',
 'werner coetzee',
 'nico abel',
 'david lilienfeld ',
 'jessica stephens',
 'a scotsman & an indian servant',
 'unknown',
 'ashley walker',
 'joe hartman',
 'ms tori lawrence',
 'brian love',
 'kinijioji vindovi',
 'ray land',
 'mary ann shands',
 'boat; occupants: t & g longhi',
 'ivo berabi',
 'clï¿½lio rosendo falcï¿½o filho',
 'd. martin',
 'elizabeth riggs',
 'a. r. davis',
 'm. worman',
 'graham hurley',
 'carl lafazio',
 'colin biggs',
 'richard  george wilson',
 '5.4 m boat  ',
 'antonio du val',
 'steven cross',
 'lidua, a male',
 'ivan gerger',
 'peter dunn',
 'richard  winer',
 'lt. james c. neal',
 'a spanish sailor',
 'male 1',
 'j. richardson',
 'teva tokoragi',
 'mr. boucaut & mr. harris',
 'edwin riley iii',
 'young boy',
 'jay worrell',
 'kim sun-sim',
 'reggie hodgson',
 'mark tisserand',
 'fernando branco de abreu',
 'clyde steamer glen sannox',
 'roger yost',
 'boat, occupants, p. groenwald and others',
 'the captainï¿½s wife',
 'elison sevo',
 'walter howe',
 'michael prather',
 'd.c. barnes',
 't. mcneill',
 'paul wilson ',
 'george e. rudd',
 '5 people swimming for shore (pilot & 4 passengers)',
 'aismerael samsel',
 'andrew masternak ',
 'adrian ruiz',
 'craig taylor',
 'mauricio guzman castaneda',
 'josï¿½ ricardo c. gouveia',
 'bernadette davis',
 'gaspar rodrigues correia',
 'sumia qio',
 'cheyne kehoe ',
 'keith helm',
 'mark butler',
 'katherine w. bourne',
 'fritz van zyl',
 'lohia raho, a male',
 'k. tracy',
 'male, a sponge diver',
 'shelby tostevin',
 'mary dunn',
 'george grant',
 'primrose whyte',
 'nolan provido',
 "boat: 69.5' trawler christy nichole ",
 'anthony aleno',
 'william siskalo',
 'gideon scheltema',
 'mcdonald van der merwe',
 'joo whan hong',
 'jamie  harrington',
 'richard chung',
 'ivan rios ',
 'mr. meyer',
 'marian leaf',
 'chase edwards',
 'john blane',
 'charles adkins',
 'charles wadra',
 '5 people claimed to have been injured by a "baby" shark',
 'a male from garvakala',
 'gordon harmer',
 'aniello mattera and giorgio allori',
 'rianto',
 'boat live n hope',
 'chucky luciano',
 'naval lt. (jg) john gibson',
 'captain tommy edward neel',
 'lawyerï¿½s secretary',
 'john dabbs',
 'paye leï¿½n salomï¿½n',
 'robert slack',
 'joel tatro',
 'p. kincaid zifflewwiggett',
 'henry brice',
 'donald jukes',
 'ross menking',
 'michael roman',
 'pablo medina',
 'al diamond',
 'richard george soden',
 "unknown, he was nabetari's companion",
 'peter weir',
 'l. molina',
 'connor lyon',
 'scott barton',
 'james smodell',
 'skiboat, occupants: gustav boettger, clive mason, keith murrison & sweis olivier',
 'lincoln alpheus',
 'elissane mobunda',
 'carl dible',
 "12' dinghy",
 'robert gault',
 '"a youth"',
 'sutto cumar mukerjea, a.k.a. haboo',
 '2 impressed seamen',
 'christine armstrong',
 'mr. moriyoshi takehara',
 'a young arab',
 'paul santos',
 'brandon murray',
 'omar karim huneidi',
 'james mckee',
 'crewman from the shepherdess',
 'bernard gill',
 'adrian esteban rafael',
 'mexican male',
 'seth mead',
 'craig rogers',
 'woody vidgens',
 'hank greenberg',
 'matthew perny',
 'an officer from h.m. forte',
 'john william eke',
 'michael waters ',
 'melvin t. toma',
 'a hungarian refugee',
 'colum tinley',
 'mateo zapeda',
 'andrew carter',
 'zebulon critchlow',
 'pat bowring',
 'rick donnis',
 'thomas mcdonald',
 'captain sanna',
 'martha hatagouei',
 'chad guthrie',
 'valery sidorovich ',
 'damien johnson',
 'julian bain',
 'alexandre rassiga',
 'elizabeth gardner',
 'young girl',
 'rick welch',
 'manuel teau',
 'eichi nakata, of the the crew of the trawler kayo maru',
 'peter saibura',
 'edward hayman',
 'don ireland',
 'ronald r. powell',
 'colleen chamberlin & scott chamberlin',
 'noel cross',
 "oar of knut dahl's boat",
 'neil davey',
 'beau martin',
 'jordan marsden',
 'pascual gurran',
 'g.r. bohan, an able seaman stationed on hmas stirling at garden island',
 'robert stinson',
 'mailia ola',
 'marcellus t. abernathy, a us soldier in the 9th coast artillery',
 'gonzales',
 'alfred victor clulow',
 'krystal magee',
 'jeff albright',
 'david silva',
 'ednaldo jose da silva',
 '4 m dinghy, occupants: cecil holmes, chris augustyn & allen varley ',
 'theo brown',
 'joshua sumait',
 'gordon hobrook',
 'don m. clark',
 'william oakley',
 'slaves',
 'esrona johnson, torres strait islander',
 'colten cicarelli',
 'rory oï¿½connor',
 'chris deford',
 'tera tetapana',
 'josh crawford',
 'elsworth smith',
 'dinghy, occupants: t. shipston, t. whitta, l cox, t. jones, r. genet & w. pearce',
 'brian derry, a naval rating',
 'male from tampa',
 'clarence ware',
 'curt vikan',
 'john williams',
 'simon bruce',
 'paul ruhle',
 'c. mooney',
 'andrew birchall',
 'j.t. hales and kenneth j. hislop, australian navy frogmen',
 'price taylor',
 'juan rodrigues galvao ',
 'preston d. soley',
 '4 crew',
 'aaron finley',
 'william f. lachmund',
 "ken o'keefe",
 'colin grey',
 'erich ritter',
 'sherrington',
 'adam johannes kriel',
 'michael guy',
 'rose sutcliffe',
 ' ben tillman homes',
 'charles adams',
 'inflatable kayak occupants:  andrej kultan & steve hopkins.\n\n',
 'wooden boat, occupants: jack bullman & keith campbell',
 'k.o.',
 'john holmes',
 'daniel viva, missionary',
 'rodney temple',
 'john butcher',
 'phil buffington',
 'austin shaw',
 'storm king; occupants - george bridge & 2 sons',
 'brooklyn daniel',
 'jason cull',
 'dan baen, jr.',
 'frank abernathy',
 'mary katherine strong',
 'ko bong-ae (female)',
 'bob earnhardt',
 'scott van burck',
 'ted roach',
 'paul dammann',
 'angus chapman',
 'bob thompson',
 "18' boat, occupants richard gunther & donald cavanaugh",
 'jodie cooper',
 'max lagao',
 'agnes novak',
 'moored fishing launch of harry lone',
 'rueben',
 "boat of scot's college rowers",
 'eric stedman',
 'avalon, a carbon kevlar monohull: 8 occupants',
 'kyle james burden',
 'sub lieut. bowyer of h.m.s. chile',
 'ted collins',
 'jack sonter',
 'abel mattos antoniou vasquez',
 'douglas christie',
 'simon letch',
 'a male & a female',
 'j. bailey',
 'len kosky',
 'mr. bennett',
 'dave marcel',
 'bianca freeman',
 'david cook',
 'captain eric hunt, the cook & a french passenger',
 'unidentified',
 '"amphibious jack" male',
 'rodney castle',
 'ryan howell',
 'john davis',
 'luciano guimarï¿½es dos santos ',
 'charles lubbe',
 'sombutize',
 'zama ndamase',
 'm.c.',
 'm.f. turnipseed',
 'indian boy',
 'alex macun',
 'johnny silva',
 'bruce eldridge',
 'jeff brown',
 'doug green',
 'hamisi njenga',
 'hermann schwebke',
 'charles anderson',
 'luis morales',
 'talon bishop',
 'james anderson',
 'hannah mayo-foster',
 'howard rosen',
 "jack o'neill",
 'leon ritson hermes',
 'llewellyn roberts',
 'terrell moore',
 'whitefield rolle',
 'bruce lang',
 'robert harms',
 '5.4 m boat, occupant: ivan anderton',
 'fijian girl',
 'damjan pecek ',
 'edward graham',
 'nunley',
 'franz mayer',
 'dawn schaumann (6.5 months pregnant)',
 'captain billy verbanas',
 'frank wacha',
 'paul lucas',
 'thomas cooke',
 'dennis patrick murphy',
 'esau & his young daughter',
 'a small boat',
 'peter garrett',
 'robin buckley (male)',
 'jose larenas-miranda',
 'william kennedy',
 '1 man',
 'neil buckley',
 'lee taplin',
 '5 children',
 'edwin f. atkins, jr.',
 'brad grissom',
 'kevin thompson',
 'beth firchau',
 'aubrey "bill" nielsen',
 'john foley',
 'donald griffin',
 'takemoto masnori',
 'romasevic',
 't riantafyllos',
 'genna hayward ',
 'craig bovim',
 'mark dotter',
 'leo a. ohai',
 'richard richardson',
 'clarence hammond',
 'eric napier cockerill',
 'mario lari',
 'steve cloke',
 '14-foot boat sintra',
 'ronald j. bishop',
 'sandrillio',
 'c.j. wickersham',
 'damon kendrick',
 'james tiffee',
 'john strand',
 'duffie fryling',
 "mr. abbas jasem (mr. kasem jasem's son)",
 'william cheatham',
 'blake tenville',
 'patrick mcinerney',
 'harry pali',
 'william mcconnell',
 'ockert stephanus heyns',
 'j. rigby',
 'a native',
 'dan hogan',
 'emile',
 'mary jane ryan',
 'glenn friedman',
 'sean m. erwin',
 'mr. keatly',
 "22' boat, occupants: saul white & charles dillione",
 'allan oppert',
 'rickey johnson',
 'jeffrey nolan',
 'alain curco-llovï¿½ra',
 'keith daldorf',
 'mrs. a.l. cummings',
 'alexander wagner',
 'jeremy mcdonagh',
 'tracie langbein',
 'michael carpenter',
 'richard bauer',
 'melanesian woman',
 'kelton beardall',
 'bryn martin',
 '3 males',
 'cheryl lowman',
 'monte gray',
 'jaringoorli',
 'kevin --',
 'halletts',
 'ronald mason',
 'matt hinton',
 'justin worral',
 'gabriel fernandez',
 'scott scherger',
 'tyna webb',
 '2 men',
 'shaun daly',
 'don dixon',
 'dominic dela cruz',
 'colin oxenbridge',
 'robert hall',
 'ivana iacaccia',
 'john hayes',
 'gregory slaughter',
 'joyce inman (royï¿½s sister)',
 'rachel king',
 'private isaac hicksled',
 'crew of anti-submarine squadron 23',
 'william f. fey',
 'sage st. clair',
 'mr. kalantar',
 'a chiefess',
 'gilbertese fisherman',
 'daniel mangel, seaman',
 'a murray islander',
 'jordan springer',
 'robert webb',
 'brian korth',
 'marc tayman',
 '6 m boat suki saki, occupants: e.c. landells & 2 friends',
 'stephan kahl',
 'david morrison, jr.',
 'michael a. reist',
 'jordan lefebvre',
 'ulrick baker or william m. baker, a sailor from h.m.s. folkestone',
 'warren rowe',
 'grant kenny',
 'belinda van schalkwyk',
 'brian anderson',
 'navid davoudabai',
 'james robinson',
 'max longhurst ',
 'parang',
 "18' boat, occupants william & leslie newton",
 'harry weatherall',
 'royce fraley',
 'mohammed rahimnejad',
 '2 usaf 4-engine planes (an hc-54 & a hc-97) each with 12 onboard collided in mid-air at low altitude and plunged into the atlantic ocean',
 'annie mills',
 'male, a ship carpenter',
 'ricky stringer',
 'kazuhiho kato',
 'keith love',
 'jack ryan',
 'liam victor',
 'lester mcdougall',
 'jacob lanskey',
 'nishi, japanese diver',
 'a.h.',
 'andranik markossian',
 'a japanese fisherman from miyagi',
 'gabe martino',
 'kaleva',
 'sergi zaloukaev',
 'paul smith, a chef',
 'andrew lewis',
 'ah hoi',
 'christopher cowan',
 'richard hegeman',
 'thomas (or tony) madison',
 'moses nunes de albuquerque junior',
 'gary johnson',
 'john cole',
 'c. pedro luis beltrï¿½n camargo ',
 'male, a teen',
 "16' cabin cruiser with 35 hp outboard motor",
 'vladimir skutelnik',
 'adam metz',
 'alexey drury',
 'rod stanley',
 'dennis & ann hadden',
 'william (or richard) schwall',
 'lo-ying-chun',
 'elena hodgson & isaac ollis',
 'chris volz',
 '?brahim karagï¿½z',
 'jerry mcinarnay',
 'victor meade',
 'jeff white',
 'wolfgang emrich',
 'richard kirby',
 'ron deguilmo',
 'louis goodman',
 'rodney orr',
 'michael van niekerk',
 'nicholas nagurney',
 'psarofa-gomenes',
 '6 m boat: occupants  stephen & andrew crust',
 'charles hutson',
 'carla podzum',
 'rodigo cesar',
 'robert walker',
 'male, a spectator',
 'two stowaways on german steamer vela',
 'cornelius conhlren',
 'chris olstad',
 'nguyen quang huynh',
 'r. vidler',
 'bob purcell',
 'launch, occupant clive whitrow, dick kuhne & jim pergola',
 'gabriel botha, a lifesaver',
 'kevin blair',
 'ham, a cambodian migrant worker',
 'callie van aswegan',
 'stanley victor locksley',
 'g.d.',
 'hyoyu kadena',
 'ruskin vest',
 'andrï¿½s tulio amaya vidal ',
 'john adams',
 'gregory moffatt',
 'boat x 2',
 'doug chesser',
 'jose alengo',
 'etuate waqa',
 'matthew zaccaria',
 'donovan kï¿½hne',
 'frï¿½dï¿½ric mousseau',
 'richard crewe',
 'alan saffery',
 '200 soldiers',
 'puerto rican',
 'theirry mercredi',
 'james may',
 'robert ford',
 'isabella carchia',
 'alfred boldner',
 'bill hawkins',
 'andrew wilson',
 'mustafa al hammadi',
 'lytton evans',
 'brad hibshman',
 'cabin boy of the bonnie dundee',
 'janardhan rughoober varma, a lifesaver',
 'charles taylor',
 'katie hester',
 'geovanni tiago barbosa ',
 'william j. goins',
 'barani, a papuan',
 'cedric coucom',
 'black male',
 'andrew, a torres strait islander',
 'adam haling ',
 'scott berry',
 'h. gebler',
 'luke baker',
 'a. robson',
 'nago, a japanese diver',
 'james waters',
 'christy wapniarski',
 'anti ketola',
 'wendall olanolan',
 'burton chamberlin',
 'david emmerton',
 'bruce cease',
 'robert wamser',
 'robert slatzer',
 'allan butcher',
 '"old cuba"',
 'roy c. kametani',
 'j.a. mckay',
 'tale meve (female)',
 'colin grant ',
 'richard spence',
 'joe bosque',
 'tristan durham',
 'joe davis',
 'tumia, a torres strait islander',
 'jeff horton',
 'jaison valentin',
 'donna hutson',
 'hudson anthony',
 '7.2 m boat. occupant kelvin travers',
 'clarence master',
 'linda ann norton',
 'stanton waterman',
 'darren kenney',
 'susan levy',
 'steve cutbirth',
 'william newbury',
 'japanese fishermen',
 'don keener',
 'bebe hall',
 'fishing',
 'a candidate for initiation',
 'michael burns',
 'keith huskisson',
 'thomas houstan',
 'joe thompson',
 'leo streng',
 'william edward brown',
 'sï¿½rgio adriano gomes silva',
 'rose mckereghan',
 'dr. ken r. markham',
 'earl yager & riley mclachlan',
 'siale sime',
 'a passenger',
 'pedro guzman',
 'hamish currie',
 'nan-tien chang',
 'john morgan',
 'julie glance ',
 'allan fripp',
 'corporal n.s. leblanc',
 'tarcisio mayora',
 'andre marais & tony jensen',
 'lowell lutz',
 'matthew pearce',
 'rick le prevost',
 'taylor holley',
 'leonardo mendoza',
 'lester stillwell',
 'monika wanis',
 'r.k. halbert',
 'roy cloke',
 'george jack',
 'derek mitchell',
 'kennon cahill',
 'inflatable dinghy, occupants: jasmine wigley, greg wilkie, phil rourke & fleur anderson',
 'tony kamage',
 'athol wearne, royal australian air force. officer',
 'scott wright',
 'donald "harvey" smith',
 'bruno junker',
 'e.s. hobson ',
 'luis henrique messias',
 'w.w. fitzsimmons',
 'theo klein',
 "paul o'leary",
 'matangusa mzize',
 'barbara green',
 'rowboat, occupant: joe whitted, christopher quevedo & 2 willard brothers',
 'kuenzler',
 'william barnes',
 'sailor ',
 'aboriginal male',
 'michael hoile',
 'tony dicks',
 'grantley butcher',
 'a dock worker',
 'marco flagg',
 'peter curruthers',
 'thomas viot',
 'christian frederick',
 'c.m',
 'norman girvan',
 'susan dornquast',
 'michael dornellas',
 'maximilliaan roual van dam',
 'william carol',
 'jane derry',
 'alan agnew',
 'mark rogotzki ',
 'spicer',
 'norman severs & horse',
 'noor-mubeen shaik',
 'robert kurrek',
 'lisa drenko',
 'michael mesiano',
 'james knight',
 '5 m aluminum boat, occupants: ben turnbull, lia & neville parker',
 'joe kool',
 'ali',
 'albert bailey',
 'les winkworth',
 'logan hamby',
 'thierry kouathe',
 'roy jeffrey stoddard',
 'rick carroll',
 'rodney baim',
 'irrwala',
 'michael knowles',
 'beverly comstock',
 'bill curtsinger',
 'luke allan',
 'paul morris',
 'alan titchenal',
 'sailed with 23 crew, half survived the explosion',
 'guy oudin',
 'robert gunn',
 'raymond odell',
 'jordan pavacich',
 'joe mcgauley',
 'fred wort',
 'sue snyder',
 'kenneth morris',
 'jerry greenberg',
 'mike rebel',
 'ian watkins',
 'barry  dawson',
 'jon harding',
 'smiles walker',
 'arnold lum',
 'william smith',
 'philip sweeting',
 'murray branson',
 'james kelley',
 'boat, occupants: captains charles anderson, emit lindberg & oscar benson',
 'captain baxter & dick chares',
 'sammy levine & his pet parrot',
 'george spencer',
 'jevan wright',
 'cole taschman',
 'zac young',
 'samuel gruber',
 'neil williams',
 'native',
 'george athanasenas',
 'randy fry',
 '2 sailors',
 'sabrina garcia',
 'eric vaughters',
 'elizabeth schelk',
 'ian marks',
 'mark skidgel',
 'john martini',
 'raymond senensi',
 'alan stevenson, jr.',
 'brian gibson ',
 'steve',
 'a german tourist',
 'kent bonde',
 'warren tooze',
 'elke specker',
 'several somali children',
 'milton shane',
 'nicolas wright',
 'ashley silverman',
 'william strathorn',
 'a solomon islander',
 'a german girl',
 "24' yacht owened by  c.l. whitrow",
 'sean grenfell',
 'a gurkha soldier',
 'louise sourisseau',
 'karen miller',
 'axel slettsten',
 'rachel gore',
 'george wainwright',
 'benigno medina navarrete ',
 'jarryd tinson ',
 'peter j. white',
 'kim bade',
 'pete swenson',
 'michel touzet',
 'joe chaney ',
 'mr. masury',
 'mary pound',
 'geoffrey zimmerman',
 'josh vaughan',
 'arturo garces',
 'carl starling',
 'johan brink',
 'bogana sabati',
 'henrietta musselwhite',
 'burris',
 'andrew cribb',
 'philip stanton',
 'leslie oswald harris',
 'ivan chandler',
 'conrad brown',
 'mark taylor',
 'allison foreman',
 'trawler jacoba, occupant jan van der bent',
 "boat: 14' sunfish. occupants josh long &  troy driscoll",
 'madi taff',
 'luke cook',
 'percy mitchell',
 'akira tuchiya',
 'a soldier',
 'giorgos',
 'jonathon lee',
 'bethany hamilton',
 'henry munson',
 'jake davis',
 'andrew rollo',
 'professor winslow',
 'kaholo',
 'lacoon',
 'kenney',
 "17' fishing boat; occupants 2 men",
 'mehdi',
 'multiple bathers',
 'emil uhlbrecht & unidentified person',
 'alistair kerr',
 'william c. lamb',
 'daniel van huysteen',
 'dinghy',
 'mark penches',

In [303]:
df[df.name=="2 usaf 4-engine planes (an hc-54 & a hc-97) each with 12 onboard collided in mid-air at low altitude and plunged into the atlantic ocean"]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal,time,species_,investigator_or_source,pdf,href
3452,1964.06.29.a,jun-1964,1964,Sea Disaster,bermuda,Hamilton,2 miles south of Castle Island Harbour entranc...,conducting a promotional film project for the ...,2 usaf 4-engine planes (an hc-54 & a hc-97) ea...,NaN,NaN,"7 rescued, 7 bodies recovered, 10 missing. Man...",True,NaN,NaN,"Washington Post, 6/30/1964; SAF Case #1295",1964.06.29-Air-Collision.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [304]:
df[df.investigator_or_source.str.startswith("The Advertiser")==True]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal,time,species_,investigator_or_source,pdf,href
210,2015.04.25,apr-2015,2015,Unprovoked,australia,South Australia,Fishery Bay,,chris blowesï¿½,M,26,Leg severed at mid-thigh,False,09h45,"White shark, 6 m","The Advertiser, 4/25/2015",2015.04.25-Blowes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
319,2014.06.18.a,jun-2014,2014,Unprovoked,australia,South Australia,"Middleton Point, Fleurieu Peninsula",body boarding,jesse mckinnon,M,15,Lacerations to knee,False,17h00,NaN,"The Advertiser, 6/19/2014",2014.06.18.a-McKinnon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
360,2014.02.08,feb-2014,2014,Unprovoked,australia,South Australia,"Goldsmith Beach, Yorke Peninsula",,sam kellett,M,28,FATAL,True,12h00,NaN,"The Advertiser, 2/9/2014",2014.02.08-Kellett.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1921,1998.12.22,dec-1998,1998,Unprovoked,australia,South Australia,Middleton Beach,standing/wading in water,megan o'leary,F,21,2 puncture wounds in left leg,False,15h30,NaN,"The Advertiser, 12/23/1998, p.3; Daily Telegra...",1998.12.22-O'Leary.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2033,1997.02.28.b,feb-1997,1997,Unprovoked,australia,Queensland,"Carrara, Nerang River",,joanna salmon,F,21,Left leg biten,False,NaN,a small shark,"The Advertiser, 3/1/1997, p.12",1997.02.28.b-Salmon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2034,1997.02.28.a,feb-1997,1997,Unprovoked,australia,Queensland,Whitsunday Passage,,gerald rauch,M,30,Left arm bitten,False,Midday,"Tiger shark, 2m to 3m","The Advertiser, 3/1/1997, p.12",1997.02.28.a-Rauch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2041,1997.01.01,jan-1997,1997,Boat,australia,Victoria,"Seal Rocks, Phillip Island",watching seals,"inflatable dinghy, occupants: jasmine wigley, ...",NaN,NaN,"No injury to occupants, shark bit 2 of the din...",False,NaN,White shark,"The Advertiser, 1/3/1997, p.7",1997.01.01-Seal-island-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2094,1996.02.04,feb-1996,1996,Unprovoked,australia,New South Wales,"Ned's Beach, Lord Howe Island",,a south australian boy,M,7,Ankles injured,False,Afternoon,"""reef shark""","The Advertiser, 2/6/1996, p.2; Daily Telegraph...",1996.02.04-boy-7.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2119,1995.09.11,sep-1995,1995,Unprovoked,australia,Western Australia,"Honeymoon Island, near Hopetown",,david alan weir,M,29,"FATAL, head, shoulder and arm severed, remains...",True,15h00,White shark,"The Advertiser, 9/13/1995, p.2; H. Edwards, pp...",1995.09.11-Weir.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2426,1989.12.02,dec-1989,1989,Invalid,australia,Queensland,Fraser Island,,michael preston,M,27,"Swept out to sea, feared taken by shark",True,NaN,NaN,"The Advertiser, 12/4/1989, p.2",1989.12.02-Preston.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3146,1971.00.00.c,jun-1971,1971,Unprovoked,australia,South Australia,Southport,,tim franklin,M,15,Severe lacerations to thigh,False,NaN,White shark,The Advertiser (undated),1971.00.00.c-Franklin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4157,1953.03.19.R,mar-1953,1953,Unprovoked,australia,South Australia,"Schnapper Rock, Kirton Point",,michael leech,M,NaN,Abrasion,False,NaN,8' shark,"The Advertiser, 3/19/1953",1953.03.19.R-Leech.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4163,1953.01.20,jan-1953,1953,Provoked,australia,South Australia,Largs Bay,,ernest lamerton,M,61,Finger bitten by hooked shark PROVOKED INCIDENT,False,NaN,NaN,"The Advertiser, 1/23/1953",1953.01.20-Lamerton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4742,1933.02.12,feb-1933,1933,Provoked,australia,South Australia,"Port River, Adelaide",,donald jukes,M,NaN,Forearm injured by hooked shark PROVOKED INCIDENT,False,NaN,Blue shark,"The Advertiser, 2/13/1933",1933.02.12-Jukes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5048,1918.03.22,mar-1918,1918,Unprovoked,australia,New South Wales,Newcastle,,arthur cook,M,NaN,"Severe laceration to arm, necessitating surgic...",False,18h00,12' shark,"The Advertiser, 3/25/1918",1918.03.22-Cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5111,1914.02.09.R,feb-1914,1914,Unprovoked,australia,South Australia,Marion Bay,standing/wading in water,mr. hasell,M,NaN,Lacerations to foot,False,NaN,said to involve a tiger shark,"The Advertiser, 2/10/1914",1914.02.09.R-Hasell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5163,1910.11.24,nov-1910,1910,Unprovoked,australia,Queensland,Mackay,,cecil smith,M,NaN,Foot bitten,False,NaN,Said to involve 9' blue shark,"The Advertiser, 11/25/1910",1910.11.24-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5176,1909.12.05,dec-1909,1909,Provoked,australia,New South Wales,Bondi,,,M,NaN,3 fingers bitten by hooked shark PROVOKED INCI...,False,NaN,7' shark,"The Advertiser, 12/9/1909",1909.12.05-Fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5202,1908.05.13,may-1908,1908,Sea Disaster,indonesia,Java,Jakarta Harbor,boat wreck,NaN,NaN,F,FATAL,True,NaN,NaN,"The Advertiser, 6/26/1908",1908.05.13-Jakarta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5241,1906.04.27.R,apr-1906,1906,Unprovoked,indonesia,Maluku Province,Aru Islands,,NaN,M,NaN,FATAL,True,NaN,NaN,"The Advertiser, 5/16/1906",1906.04.27.R-Aru-Islands.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5250,1905.12.29,dec-1905,1905,Invalid,australia,Western Australia,Geraldton,,hugh carroll,M,NaN,"""Bad wound in the leg"" - 7-ft shark caught in ...",False,NaN,Shark involvement not confirmed,"The Advertiser, 12/30/1905",1905.12.29-Carroll.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5274,1904.01.23,jan-1904,1904,Unprovoked,new caledonia,South Province,Noumea,,charley smith,M,NaN,FATAL,True,NaN,NaN,"The Advertiser, 2/4/1904",1904.01.23-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5281,1903.06.21,jun-1903,1903,Unprovoked,australia,New South Wales,Georges River,,william price,M,NaN,FATAL,True,NaN,NaN,"The Advertiser, 6/22/1903",1903.06.21-Price.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5289,1902.11.10,nov-1902,1902,Unprovoked,australia,New South Wales,"Middle Harbour, Sydney",,howard dent,M,17,FATAL,True,Afternoon,NaN,"The Advertiser, 11/11/1902",1902.11.10-Dent.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5300,1902.01.25.R,jan-1902,1902,Unprovoked,australia,New South Wales,Kerosene Bay,dangling feet in the water,john ogier,M,NaN,FATAL,True,NaN,NaN,"The Advertiser, 1/25/1902",1902.01.22-Ogier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5445,1891.12.22.R,dec-1891,1891,Unprovoked,new zealand,North Island,"Manukau Harbor, 6 miles south of Auckland",,henry jacobson,M,NaN,Hand bitten,False,NaN,NaN,"The Advertiser, 1/1/1892",1891.12.22.R-Jacobson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
5878,ND-1940,jun-1930,0,Unprovoked,papua new guinea,Morobe Province,Simbang,,,M,NaN,FATAL,True,NaN,NaN,"The Advertiser (Adelaide), 6/2/1933",ND-0140-NewGuinea.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

### Time

In [313]:
df.time.nunique()

251

In [314]:
df.time.unique()

array(['13h00', '11h00', '10h43', 'nan', '15h15', '14h30', '15h40',
       '17h00', '15h00', '14h00', '16h00', '11h30', '12h00', '19h05',
       '1300', '10h00', '', '22h00', '16h20', '14h34', '15h25', '14h55',
       '06h00', '17h30', '08h30', '8h00', '15h45', '18h00', '17h46',
       '13h20', '15h49', '07h00', '08h00', '10h45', '19h00', '13h30',
       '00h00', '12h30', '10h30', '18h15', '04h00', '14h50', '13h50',
       '19h20', '10h25', '16h50', '16h45', '15h52', '07h30', '06h15',
       '14h40', '19h45', '17h10', '15h30', '10h10', '08h45', '20h00',
       '09h00', '12h10', '18h05', '19h30', '11h41', '12h25', '09h30',
       '17h51', '16h12', '12h45', '10h50', '13h45', '14h15', '16h30',
       '09h45', '11h45', '10h20', '18h30', '06h45', '05h00', '03h30',
       '06h30', '11h15', '17h20', '18h45', '16h40', '16h18', '11h10',
       '17h50', '17h01', '10h15', '09h57', '08h20', '17h58', '20h30',
       '15h19', '10h55', '15h55', '23h00', '12h40', '13h55', '16h05',
       '14h10', '15h20', '12h50', '14h45', '13h40', '13h24', '09h40',
       '11h40', '08h10', '15h56', '14h20', '07h56', '1600', '17h17',
       '16h35', '09h05', '07h15', '07h20', '19h28', '12h38', '05h50',
       '15h50', '11h05', '05h45', '13h25', '09h50', '12h20', '13h26',
       '09h11', '12h15', '13h15', '17h45', '18h20', '10h40', '15h35',
       '13h51', '08h50', '08h05', '19h15', '10h35', '15h44', '02h00',
       '21h00', '1545', '09h35', '10h27', '10h16', '07h45', '09h20',
       '12h05', '14h21', '18h50', '15h53', '11h115', '08h15', '13h42',
       '20h15', '12h39', '17h35', '07h05', '  ', '13h05', '11h50',
       '17h55', '22h30', '17h15', '16h10', '06h10', '16h15', '07h08',
       '03h00', '12h02', '12h55', '16h14', '17h11', '00h30', '14h37',
       '10h07', '13h53', '11h55', '13h23', '02h30', '08h40', '11h56',
       '14h35', ' ', '07h50', '14h25', '13h345', '06h47', '18h40',
       '13h14', '13h06', '11h20', '12h34', '11h53', '8:', '12h46',
       '12h48', '17h42', '12h35', '11h57', '17h40', '11h25', '18h25',
       '10h28', '09h15', '14h16', '09h55', '15h05', '11h48', '07h19',
       '13h37', '11h06', '18h30?', '11h58', '11h51', '18h12', '07h10',
       '07h40', '12h33', '15h06', '12h54', '16h55', '05h40', '21h30',
       '08h57', '0600', '08h35', '10h22', '02h45', '18h10', '08h55',
       ' 14h00', '06h50', '01h00', '23h30', '07h32', '13h10', '19h35',
       '13h35', '01h32', '16h23', '12h00.', '19h10', '16h25', '1',
       '19h55', '01h30', '05h30', '08h58', '01h50'], dtype=object)

In [307]:
df.time=df.time.str.lower()

In [312]:
df.time=[re.sub(r'late afternoon|just before sundown|mid afternoon|before daybreak|sunset', "17h00", str(x)) for x in df.time]
df.time=[re.sub(r'after noon|afternoon|early afternoon|after lunch', "14h00", str(x)) for x in df.time]
df.time=[re.sub(r'morning|early morning|daybreak|dawn','8h00', str(x)) for x in df.time]
df.time=[re.sub(r'midnight', "00h00", str(x)) for x in df.time]
df.time=[re.sub(r'evening|after dark|early evening|nightfall', "20h00", str(x)) for x in df.time]
df.time=[re.sub(r'noon|just before noon|midday|lunchtime|late morning', "12h00", str(x)) for x in df.time]
df.time=[re.sub(r'late night', "23h00", str(x)) for x in df.time]
##"2 hrs before sunset"|"shortly before dusk" sometime between 06h00 & 08hoo | between 06h00 & 
df.time=[re.sub(r'daytime|just before |>|after |<|\"|x|j|', "", str(x)) for x in df.time]
df.time=[re.sub(r'dark|p.m.|ï¿½ |am|500|a.m.|night|mid|   ', "", str(x)) for x in df.time]
df.time=[re.sub(r' \/.*|--.*|-.*|\w+ .*', "", str(x)) for x in df.time]
df.time=df.time.replace("dusk", "02h00")
df.time=df.time.replace("830", "")